// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/display.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum VSDisplayMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case extend // = 1
  case mirror // = 2
  case existing // = 3
  case headlessPrimary // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .extend
    case 2: self = .mirror
    case 3: self = .existing
    case 4: self = .headlessPrimary
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .extend: return 1
    case .mirror: return 2
    case .existing: return 3
    case .headlessPrimary: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSDisplayMode] = [
    .unspecified,
    .extend,
    .mirror,
    .existing,
    .headlessPrimary,
  ]

}

public struct VSDisplayDescriptor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var displayID: String = String()

  public var name: String = String()

  public var logicalSize: VSDimensions {
    get {return _logicalSize ?? VSDimensions()}
    set {_logicalSize = newValue}
  }
  /// Returns true if `logicalSize` has been explicitly set.
  public var hasLogicalSize: Bool {return self._logicalSize != nil}
  /// Clears the value of `logicalSize`. Subsequent reads from it will return its default value.
  public mutating func clearLogicalSize() {self._logicalSize = nil}

  public var scaleFactor: Double = 0

  public var isPrimary: Bool = false

  public var isVirtual: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _logicalSize: VSDimensions? = nil
}

public struct VSListDisplaysRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSListDisplaysResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var displays: [VSDisplayDescriptor] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSStartDisplayRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mode: VSDisplayMode = .unspecified

  public var sourceDisplayID: String = String()

  public var requestedLogicalSize: VSDimensions {
    get {return _requestedLogicalSize ?? VSDimensions()}
    set {_requestedLogicalSize = newValue}
  }
  /// Returns true if `requestedLogicalSize` has been explicitly set.
  public var hasRequestedLogicalSize: Bool {return self._requestedLogicalSize != nil}
  /// Clears the value of `requestedLogicalSize`. Subsequent reads from it will return its default value.
  public mutating func clearRequestedLogicalSize() {self._requestedLogicalSize = nil}

  public var requestedScaleFactor: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _requestedLogicalSize: VSDimensions? = nil
}

public struct VSStartDisplayResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accepted: Bool = false

  public var display: VSDisplayDescriptor {
    get {return _display ?? VSDisplayDescriptor()}
    set {_display = newValue}
  }
  /// Returns true if `display` has been explicitly set.
  public var hasDisplay: Bool {return self._display != nil}
  /// Clears the value of `display`. Subsequent reads from it will return its default value.
  public mutating func clearDisplay() {self._display = nil}

  public var rejectionReason: String = String()

  public var streamID: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _display: VSDisplayDescriptor? = nil
}

public struct VSStopDisplay: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var displayID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSDisplayChanged: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var display: VSDisplayDescriptor {
    get {return _display ?? VSDisplayDescriptor()}
    set {_display = newValue}
  }
  /// Returns true if `display` has been explicitly set.
  public var hasDisplay: Bool {return self._display != nil}
  /// Clears the value of `display`. Subsequent reads from it will return its default value.
  public mutating func clearDisplay() {self._display = nil}

  public var rotationDegrees: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _display: VSDisplayDescriptor? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSDisplayMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DISPLAY_MODE_UNSPECIFIED\0\u{1}DISPLAY_MODE_EXTEND\0\u{1}DISPLAY_MODE_MIRROR\0\u{1}DISPLAY_MODE_EXISTING\0\u{1}DISPLAY_MODE_HEADLESS_PRIMARY\0")
}

extension VSDisplayDescriptor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DisplayDescriptor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}display_id\0\u{1}name\0\u{3}logical_size\0\u{3}scale_factor\0\u{3}is_primary\0\u{3}is_virtual\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.displayID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._logicalSize) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.scaleFactor) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.isPrimary) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.isVirtual) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.displayID.isEmpty {
      try visitor.visitSingularStringField(value: self.displayID, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try { if let v = self._logicalSize {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.scaleFactor.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.scaleFactor, fieldNumber: 4)
    }
    if self.isPrimary != false {
      try visitor.visitSingularBoolField(value: self.isPrimary, fieldNumber: 5)
    }
    if self.isVirtual != false {
      try visitor.visitSingularBoolField(value: self.isVirtual, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSDisplayDescriptor, rhs: VSDisplayDescriptor) -> Bool {
    if lhs.displayID != rhs.displayID {return false}
    if lhs.name != rhs.name {return false}
    if lhs._logicalSize != rhs._logicalSize {return false}
    if lhs.scaleFactor != rhs.scaleFactor {return false}
    if lhs.isPrimary != rhs.isPrimary {return false}
    if lhs.isVirtual != rhs.isVirtual {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSListDisplaysRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListDisplaysRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSListDisplaysRequest, rhs: VSListDisplaysRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSListDisplaysResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListDisplaysResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}displays\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.displays) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.displays.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.displays, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSListDisplaysResponse, rhs: VSListDisplaysResponse) -> Bool {
    if lhs.displays != rhs.displays {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSStartDisplayRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartDisplayRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mode\0\u{3}source_display_id\0\u{3}requested_logical_size\0\u{3}requested_scale_factor\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sourceDisplayID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._requestedLogicalSize) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.requestedScaleFactor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.mode != .unspecified {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 1)
    }
    if !self.sourceDisplayID.isEmpty {
      try visitor.visitSingularStringField(value: self.sourceDisplayID, fieldNumber: 2)
    }
    try { if let v = self._requestedLogicalSize {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.requestedScaleFactor.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.requestedScaleFactor, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSStartDisplayRequest, rhs: VSStartDisplayRequest) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.sourceDisplayID != rhs.sourceDisplayID {return false}
    if lhs._requestedLogicalSize != rhs._requestedLogicalSize {return false}
    if lhs.requestedScaleFactor != rhs.requestedScaleFactor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSStartDisplayResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartDisplayResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}accepted\0\u{1}display\0\u{3}rejection_reason\0\u{3}stream_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._display) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 1)
    }
    try { if let v = self._display {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 3)
    }
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSStartDisplayResponse, rhs: VSStartDisplayResponse) -> Bool {
    if lhs.accepted != rhs.accepted {return false}
    if lhs._display != rhs._display {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.streamID != rhs.streamID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSStopDisplay: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StopDisplay"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}display_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.displayID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.displayID.isEmpty {
      try visitor.visitSingularStringField(value: self.displayID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSStopDisplay, rhs: VSStopDisplay) -> Bool {
    if lhs.displayID != rhs.displayID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSDisplayChanged: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DisplayChanged"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}display\0\u{3}rotation_degrees\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._display) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.rotationDegrees) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._display {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.rotationDegrees != 0 {
      try visitor.visitSingularUInt32Field(value: self.rotationDegrees, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSDisplayChanged, rhs: VSDisplayChanged) -> Bool {
    if lhs._display != rhs._display {return false}
    if lhs.rotationDegrees != rhs.rotationDegrees {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
