// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/error.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum VSProtocolErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case unsupportedVersion // = 1
  case malformedMessage // = 2
  case unsupportedCapability // = 3
  case invalidState // = 4
  case unauthorized // = 5
  case resourceExhausted // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .unsupportedVersion
    case 2: self = .malformedMessage
    case 3: self = .unsupportedCapability
    case 4: self = .invalidState
    case 5: self = .unauthorized
    case 6: self = .resourceExhausted
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .unsupportedVersion: return 1
    case .malformedMessage: return 2
    case .unsupportedCapability: return 3
    case .invalidState: return 4
    case .unauthorized: return 5
    case .resourceExhausted: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSProtocolErrorCode] = [
    .unspecified,
    .unsupportedVersion,
    .malformedMessage,
    .unsupportedCapability,
    .invalidState,
    .unauthorized,
    .resourceExhausted,
  ]

}

public struct VSProtocolError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var code: VSProtocolErrorCode = .unspecified

  public var message: String = String()

  public var retryable: Bool = false

  public var component: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSProtocolErrorCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PROTOCOL_ERROR_CODE_UNSPECIFIED\0\u{1}PROTOCOL_ERROR_CODE_UNSUPPORTED_VERSION\0\u{1}PROTOCOL_ERROR_CODE_MALFORMED_MESSAGE\0\u{1}PROTOCOL_ERROR_CODE_UNSUPPORTED_CAPABILITY\0\u{1}PROTOCOL_ERROR_CODE_INVALID_STATE\0\u{1}PROTOCOL_ERROR_CODE_UNAUTHORIZED\0\u{1}PROTOCOL_ERROR_CODE_RESOURCE_EXHAUSTED\0")
}

extension VSProtocolError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProtocolError"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0\u{1}retryable\0\u{1}component\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.retryable) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.component) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != .unspecified {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.retryable != false {
      try visitor.visitSingularBoolField(value: self.retryable, fieldNumber: 3)
    }
    if !self.component.isEmpty {
      try visitor.visitSingularStringField(value: self.component, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSProtocolError, rhs: VSProtocolError) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.retryable != rhs.retryable {return false}
    if lhs.component != rhs.component {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
