// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/pairing.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct VSPairingOffer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var offerID: Data = Data()

  public var oneTimeCredential: Data = Data()

  public var expiresAtUnixSeconds: UInt64 = 0

  public var hostPublicKey: Data = Data()

  public var hostIdentity: VSDeviceIdentity {
    get {return _hostIdentity ?? VSDeviceIdentity()}
    set {_hostIdentity = newValue}
  }
  /// Returns true if `hostIdentity` has been explicitly set.
  public var hasHostIdentity: Bool {return self._hostIdentity != nil}
  /// Clears the value of `hostIdentity`. Subsequent reads from it will return its default value.
  public mutating func clearHostIdentity() {self._hostIdentity = nil}

  public var challenge: Data = Data()

  public var ephemeralPublicKey: Data = Data()

  public var signatureAlgorithms: [VSSignatureAlgorithm] = []

  public var keyAgreementAlgorithms: [VSKeyAgreementAlgorithm] = []

  public var aeadAlgorithms: [VSAeadAlgorithm] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _hostIdentity: VSDeviceIdentity? = nil
}

public struct VSPairingRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var offerID: Data = Data()

  public var deviceID: String = String()

  public var deviceName: String = String()

  public var devicePublicKey: Data = Data()

  public var deviceIdentity: VSDeviceIdentity {
    get {return _deviceIdentity ?? VSDeviceIdentity()}
    set {_deviceIdentity = newValue}
  }
  /// Returns true if `deviceIdentity` has been explicitly set.
  public var hasDeviceIdentity: Bool {return self._deviceIdentity != nil}
  /// Clears the value of `deviceIdentity`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceIdentity() {self._deviceIdentity = nil}

  public var proof: VSPairingProof {
    get {return _proof ?? VSPairingProof()}
    set {_proof = newValue}
  }
  /// Returns true if `proof` has been explicitly set.
  public var hasProof: Bool {return self._proof != nil}
  /// Clears the value of `proof`. Subsequent reads from it will return its default value.
  public mutating func clearProof() {self._proof = nil}

  public var bootstrapMac: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _deviceIdentity: VSDeviceIdentity? = nil
  fileprivate var _proof: VSPairingProof? = nil
}

public struct VSPairingResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accepted: Bool = false

  public var deviceID: String = String()

  public var deviceCredential: Data = Data()

  public var rejectionReason: String = String()

  public var hostProof: VSPairingProof {
    get {return _hostProof ?? VSPairingProof()}
    set {_hostProof = newValue}
  }
  /// Returns true if `hostProof` has been explicitly set.
  public var hasHostProof: Bool {return self._hostProof != nil}
  /// Clears the value of `hostProof`. Subsequent reads from it will return its default value.
  public mutating func clearHostProof() {self._hostProof = nil}

  public var encryptedDeviceCredential: Data = Data()

  public var credentialNonce: Data = Data()

  public var sessionKeyID: String = String()

  public var sessionKeyEpoch: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _hostProof: VSPairingProof? = nil
}

public struct VSDeviceRevoked: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: String = String()

  public var reasonCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSPairingOffer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairingOffer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}offer_id\0\u{3}one_time_credential\0\u{3}expires_at_unix_seconds\0\u{3}host_public_key\0\u{3}host_identity\0\u{1}challenge\0\u{3}ephemeral_public_key\0\u{3}signature_algorithms\0\u{3}key_agreement_algorithms\0\u{3}aead_algorithms\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.offerID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.oneTimeCredential) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.expiresAtUnixSeconds) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.hostPublicKey) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._hostIdentity) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.challenge) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.ephemeralPublicKey) }()
      case 8: try { try decoder.decodeRepeatedEnumField(value: &self.signatureAlgorithms) }()
      case 9: try { try decoder.decodeRepeatedEnumField(value: &self.keyAgreementAlgorithms) }()
      case 10: try { try decoder.decodeRepeatedEnumField(value: &self.aeadAlgorithms) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.offerID.isEmpty {
      try visitor.visitSingularBytesField(value: self.offerID, fieldNumber: 1)
    }
    if !self.oneTimeCredential.isEmpty {
      try visitor.visitSingularBytesField(value: self.oneTimeCredential, fieldNumber: 2)
    }
    if self.expiresAtUnixSeconds != 0 {
      try visitor.visitSingularUInt64Field(value: self.expiresAtUnixSeconds, fieldNumber: 3)
    }
    if !self.hostPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.hostPublicKey, fieldNumber: 4)
    }
    try { if let v = self._hostIdentity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.challenge.isEmpty {
      try visitor.visitSingularBytesField(value: self.challenge, fieldNumber: 6)
    }
    if !self.ephemeralPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.ephemeralPublicKey, fieldNumber: 7)
    }
    if !self.signatureAlgorithms.isEmpty {
      try visitor.visitPackedEnumField(value: self.signatureAlgorithms, fieldNumber: 8)
    }
    if !self.keyAgreementAlgorithms.isEmpty {
      try visitor.visitPackedEnumField(value: self.keyAgreementAlgorithms, fieldNumber: 9)
    }
    if !self.aeadAlgorithms.isEmpty {
      try visitor.visitPackedEnumField(value: self.aeadAlgorithms, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSPairingOffer, rhs: VSPairingOffer) -> Bool {
    if lhs.offerID != rhs.offerID {return false}
    if lhs.oneTimeCredential != rhs.oneTimeCredential {return false}
    if lhs.expiresAtUnixSeconds != rhs.expiresAtUnixSeconds {return false}
    if lhs.hostPublicKey != rhs.hostPublicKey {return false}
    if lhs._hostIdentity != rhs._hostIdentity {return false}
    if lhs.challenge != rhs.challenge {return false}
    if lhs.ephemeralPublicKey != rhs.ephemeralPublicKey {return false}
    if lhs.signatureAlgorithms != rhs.signatureAlgorithms {return false}
    if lhs.keyAgreementAlgorithms != rhs.keyAgreementAlgorithms {return false}
    if lhs.aeadAlgorithms != rhs.aeadAlgorithms {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSPairingRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairingRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}offer_id\0\u{3}device_id\0\u{3}device_name\0\u{3}device_public_key\0\u{3}device_identity\0\u{1}proof\0\u{3}bootstrap_mac\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.offerID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.deviceName) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.devicePublicKey) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._deviceIdentity) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._proof) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.bootstrapMac) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.offerID.isEmpty {
      try visitor.visitSingularBytesField(value: self.offerID, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 2)
    }
    if !self.deviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceName, fieldNumber: 3)
    }
    if !self.devicePublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.devicePublicKey, fieldNumber: 4)
    }
    try { if let v = self._deviceIdentity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._proof {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if !self.bootstrapMac.isEmpty {
      try visitor.visitSingularBytesField(value: self.bootstrapMac, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSPairingRequest, rhs: VSPairingRequest) -> Bool {
    if lhs.offerID != rhs.offerID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.deviceName != rhs.deviceName {return false}
    if lhs.devicePublicKey != rhs.devicePublicKey {return false}
    if lhs._deviceIdentity != rhs._deviceIdentity {return false}
    if lhs._proof != rhs._proof {return false}
    if lhs.bootstrapMac != rhs.bootstrapMac {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSPairingResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairingResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}accepted\0\u{3}device_id\0\u{3}device_credential\0\u{3}rejection_reason\0\u{3}host_proof\0\u{3}encrypted_device_credential\0\u{3}credential_nonce\0\u{3}session_key_id\0\u{3}session_key_epoch\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.deviceCredential) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._hostProof) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.encryptedDeviceCredential) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.credentialNonce) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.sessionKeyID) }()
      case 9: try { try decoder.decodeSingularUInt64Field(value: &self.sessionKeyEpoch) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 2)
    }
    if !self.deviceCredential.isEmpty {
      try visitor.visitSingularBytesField(value: self.deviceCredential, fieldNumber: 3)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 4)
    }
    try { if let v = self._hostProof {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.encryptedDeviceCredential.isEmpty {
      try visitor.visitSingularBytesField(value: self.encryptedDeviceCredential, fieldNumber: 6)
    }
    if !self.credentialNonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.credentialNonce, fieldNumber: 7)
    }
    if !self.sessionKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionKeyID, fieldNumber: 8)
    }
    if self.sessionKeyEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionKeyEpoch, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSPairingResult, rhs: VSPairingResult) -> Bool {
    if lhs.accepted != rhs.accepted {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.deviceCredential != rhs.deviceCredential {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs._hostProof != rhs._hostProof {return false}
    if lhs.encryptedDeviceCredential != rhs.encryptedDeviceCredential {return false}
    if lhs.credentialNonce != rhs.credentialNonce {return false}
    if lhs.sessionKeyID != rhs.sessionKeyID {return false}
    if lhs.sessionKeyEpoch != rhs.sessionKeyEpoch {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSDeviceRevoked: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceRevoked"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{3}reason_code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 1)
    }
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSDeviceRevoked, rhs: VSDeviceRevoked) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
