// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/session.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum VSCapability: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case displayMirror // = 1
  case virtualDisplay // = 2
  case touch // = 3
  case keyboard // = 4
  case pointer // = 5
  case stylus // = 6
  case telemetry // = 7
  case sessionResume // = 8
  case deviceIdentity // = 9
  case endToEndEncryption // = 10
  case keyRotation // = 11
  case replayProtection // = 12
  case audio // = 13
  case clipboard // = 14
  case fileTransfer // = 15
  case hdrVideo // = 16
  case colorManagement // = 17
  case multiDisplay // = 18
  case multiClient // = 19
  case hostActions // = 20
  case wakeHost // = 21
  case managedConfiguration // = 22
  case mediaRecordFragmentation // = 23
  case clientVideoControl // = 24

  /// Requires CAPABILITY_STYLUS and enables StylusEvent tool kind, barrel
  /// buttons, and explicit contact/proximity state.
  case stylusExtended // = 25

  /// Enables lifecycle-scoped ControllerEvent input. Receivers must neutralize
  /// admitted controller state when its lifecycle or session ends.
  case controller // = 26
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .displayMirror
    case 2: self = .virtualDisplay
    case 3: self = .touch
    case 4: self = .keyboard
    case 5: self = .pointer
    case 6: self = .stylus
    case 7: self = .telemetry
    case 8: self = .sessionResume
    case 9: self = .deviceIdentity
    case 10: self = .endToEndEncryption
    case 11: self = .keyRotation
    case 12: self = .replayProtection
    case 13: self = .audio
    case 14: self = .clipboard
    case 15: self = .fileTransfer
    case 16: self = .hdrVideo
    case 17: self = .colorManagement
    case 18: self = .multiDisplay
    case 19: self = .multiClient
    case 20: self = .hostActions
    case 21: self = .wakeHost
    case 22: self = .managedConfiguration
    case 23: self = .mediaRecordFragmentation
    case 24: self = .clientVideoControl
    case 25: self = .stylusExtended
    case 26: self = .controller
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .displayMirror: return 1
    case .virtualDisplay: return 2
    case .touch: return 3
    case .keyboard: return 4
    case .pointer: return 5
    case .stylus: return 6
    case .telemetry: return 7
    case .sessionResume: return 8
    case .deviceIdentity: return 9
    case .endToEndEncryption: return 10
    case .keyRotation: return 11
    case .replayProtection: return 12
    case .audio: return 13
    case .clipboard: return 14
    case .fileTransfer: return 15
    case .hdrVideo: return 16
    case .colorManagement: return 17
    case .multiDisplay: return 18
    case .multiClient: return 19
    case .hostActions: return 20
    case .wakeHost: return 21
    case .managedConfiguration: return 22
    case .mediaRecordFragmentation: return 23
    case .clientVideoControl: return 24
    case .stylusExtended: return 25
    case .controller: return 26
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSCapability] = [
    .unspecified,
    .displayMirror,
    .virtualDisplay,
    .touch,
    .keyboard,
    .pointer,
    .stylus,
    .telemetry,
    .sessionResume,
    .deviceIdentity,
    .endToEndEncryption,
    .keyRotation,
    .replayProtection,
    .audio,
    .clipboard,
    .fileTransfer,
    .hdrVideo,
    .colorManagement,
    .multiDisplay,
    .multiClient,
    .hostActions,
    .wakeHost,
    .managedConfiguration,
    .mediaRecordFragmentation,
    .clientVideoControl,
    .stylusExtended,
    .controller,
  ]

}

public struct VSClientHello: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var supportedProtocols: VSProtocolRange {
    get {return _storage._supportedProtocols ?? VSProtocolRange()}
    set {_uniqueStorage()._supportedProtocols = newValue}
  }
  /// Returns true if `supportedProtocols` has been explicitly set.
  public var hasSupportedProtocols: Bool {return _storage._supportedProtocols != nil}
  /// Clears the value of `supportedProtocols`. Subsequent reads from it will return its default value.
  public mutating func clearSupportedProtocols() {_uniqueStorage()._supportedProtocols = nil}

  public var deviceID: String {
    get {return _storage._deviceID}
    set {_uniqueStorage()._deviceID = newValue}
  }

  public var deviceName: String {
    get {return _storage._deviceName}
    set {_uniqueStorage()._deviceName = newValue}
  }

  public var capabilities: [VSCapability] {
    get {return _storage._capabilities}
    set {_uniqueStorage()._capabilities = newValue}
  }

  public var codecs: [VSCodec] {
    get {return _storage._codecs}
    set {_uniqueStorage()._codecs = newValue}
  }

  public var transports: [VSTransportKind] {
    get {return _storage._transports}
    set {_uniqueStorage()._transports = newValue}
  }

  public var resourceLimits: VSResourceLimits {
    get {return _storage._resourceLimits ?? VSResourceLimits()}
    set {_uniqueStorage()._resourceLimits = newValue}
  }
  /// Returns true if `resourceLimits` has been explicitly set.
  public var hasResourceLimits: Bool {return _storage._resourceLimits != nil}
  /// Clears the value of `resourceLimits`. Subsequent reads from it will return its default value.
  public mutating func clearResourceLimits() {_uniqueStorage()._resourceLimits = nil}

  public var videoDecodeCapabilities: [VSVideoDecodeCapability] {
    get {return _storage._videoDecodeCapabilities}
    set {_uniqueStorage()._videoDecodeCapabilities = newValue}
  }

  public var requiredCapabilities: [VSCapability] {
    get {return _storage._requiredCapabilities}
    set {_uniqueStorage()._requiredCapabilities = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct VSHostHello: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var selectedProtocol: UInt32 = 0

  public var hostID: String = String()

  public var hostName: String = String()

  public var capabilities: [VSCapability] = []

  public var codecs: [VSCodec] = []

  public var resourceLimits: VSResourceLimits {
    get {return _resourceLimits ?? VSResourceLimits()}
    set {_resourceLimits = newValue}
  }
  /// Returns true if `resourceLimits` has been explicitly set.
  public var hasResourceLimits: Bool {return self._resourceLimits != nil}
  /// Clears the value of `resourceLimits`. Subsequent reads from it will return its default value.
  public mutating func clearResourceLimits() {self._resourceLimits = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _resourceLimits: VSResourceLimits? = nil
}

public struct VSSessionAccepted: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sessionID: Data = Data()

  public var sessionEpoch: UInt64 = 0

  public var heartbeatIntervalMs: UInt32 = 0

  public var negotiatedCapabilities: [VSCapability] = []

  public var negotiatedResourceLimits: VSResourceLimits {
    get {return _negotiatedResourceLimits ?? VSResourceLimits()}
    set {_negotiatedResourceLimits = newValue}
  }
  /// Returns true if `negotiatedResourceLimits` has been explicitly set.
  public var hasNegotiatedResourceLimits: Bool {return self._negotiatedResourceLimits != nil}
  /// Clears the value of `negotiatedResourceLimits`. Subsequent reads from it will return its default value.
  public mutating func clearNegotiatedResourceLimits() {self._negotiatedResourceLimits = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _negotiatedResourceLimits: VSResourceLimits? = nil
}

public struct VSSessionRejected: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reasonCode: String = String()

  public var message: String = String()

  public var retryable: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSPing: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sequence: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSPong: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sequence: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSResumeSessionRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sessionID: Data = Data()

  public var previousSessionEpoch: UInt64 = 0

  public var lastReceivedMessageID: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSResumeSessionResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accepted: Bool = false

  public var sessionEpoch: UInt64 = 0

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSDisconnectNotice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reasonCode: String = String()

  public var mayResume: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSCapability: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CAPABILITY_UNSPECIFIED\0\u{1}CAPABILITY_DISPLAY_MIRROR\0\u{1}CAPABILITY_VIRTUAL_DISPLAY\0\u{1}CAPABILITY_TOUCH\0\u{1}CAPABILITY_KEYBOARD\0\u{1}CAPABILITY_POINTER\0\u{1}CAPABILITY_STYLUS\0\u{1}CAPABILITY_TELEMETRY\0\u{1}CAPABILITY_SESSION_RESUME\0\u{1}CAPABILITY_DEVICE_IDENTITY\0\u{1}CAPABILITY_END_TO_END_ENCRYPTION\0\u{1}CAPABILITY_KEY_ROTATION\0\u{1}CAPABILITY_REPLAY_PROTECTION\0\u{1}CAPABILITY_AUDIO\0\u{1}CAPABILITY_CLIPBOARD\0\u{1}CAPABILITY_FILE_TRANSFER\0\u{1}CAPABILITY_HDR_VIDEO\0\u{1}CAPABILITY_COLOR_MANAGEMENT\0\u{1}CAPABILITY_MULTI_DISPLAY\0\u{1}CAPABILITY_MULTI_CLIENT\0\u{1}CAPABILITY_HOST_ACTIONS\0\u{1}CAPABILITY_WAKE_HOST\0\u{1}CAPABILITY_MANAGED_CONFIGURATION\0\u{1}CAPABILITY_MEDIA_RECORD_FRAGMENTATION\0\u{1}CAPABILITY_CLIENT_VIDEO_CONTROL\0\u{1}CAPABILITY_STYLUS_EXTENDED\0\u{1}CAPABILITY_CONTROLLER\0")
}

extension VSClientHello: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClientHello"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}supported_protocols\0\u{3}device_id\0\u{3}device_name\0\u{1}capabilities\0\u{1}codecs\0\u{1}transports\0\u{3}resource_limits\0\u{3}video_decode_capabilities\0\u{3}required_capabilities\0")

  fileprivate class _StorageClass {
    var _supportedProtocols: VSProtocolRange? = nil
    var _deviceID: String = String()
    var _deviceName: String = String()
    var _capabilities: [VSCapability] = []
    var _codecs: [VSCodec] = []
    var _transports: [VSTransportKind] = []
    var _resourceLimits: VSResourceLimits? = nil
    var _videoDecodeCapabilities: [VSVideoDecodeCapability] = []
    var _requiredCapabilities: [VSCapability] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _supportedProtocols = source._supportedProtocols
      _deviceID = source._deviceID
      _deviceName = source._deviceName
      _capabilities = source._capabilities
      _codecs = source._codecs
      _transports = source._transports
      _resourceLimits = source._resourceLimits
      _videoDecodeCapabilities = source._videoDecodeCapabilities
      _requiredCapabilities = source._requiredCapabilities
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._supportedProtocols) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._deviceID) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._deviceName) }()
        case 4: try { try decoder.decodeRepeatedEnumField(value: &_storage._capabilities) }()
        case 5: try { try decoder.decodeRepeatedEnumField(value: &_storage._codecs) }()
        case 6: try { try decoder.decodeRepeatedEnumField(value: &_storage._transports) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._resourceLimits) }()
        case 8: try { try decoder.decodeRepeatedMessageField(value: &_storage._videoDecodeCapabilities) }()
        case 9: try { try decoder.decodeRepeatedEnumField(value: &_storage._requiredCapabilities) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._supportedProtocols {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._deviceID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._deviceID, fieldNumber: 2)
      }
      if !_storage._deviceName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._deviceName, fieldNumber: 3)
      }
      if !_storage._capabilities.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._capabilities, fieldNumber: 4)
      }
      if !_storage._codecs.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._codecs, fieldNumber: 5)
      }
      if !_storage._transports.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._transports, fieldNumber: 6)
      }
      try { if let v = _storage._resourceLimits {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if !_storage._videoDecodeCapabilities.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._videoDecodeCapabilities, fieldNumber: 8)
      }
      if !_storage._requiredCapabilities.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._requiredCapabilities, fieldNumber: 9)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSClientHello, rhs: VSClientHello) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._supportedProtocols != rhs_storage._supportedProtocols {return false}
        if _storage._deviceID != rhs_storage._deviceID {return false}
        if _storage._deviceName != rhs_storage._deviceName {return false}
        if _storage._capabilities != rhs_storage._capabilities {return false}
        if _storage._codecs != rhs_storage._codecs {return false}
        if _storage._transports != rhs_storage._transports {return false}
        if _storage._resourceLimits != rhs_storage._resourceLimits {return false}
        if _storage._videoDecodeCapabilities != rhs_storage._videoDecodeCapabilities {return false}
        if _storage._requiredCapabilities != rhs_storage._requiredCapabilities {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSHostHello: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostHello"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}selected_protocol\0\u{3}host_id\0\u{3}host_name\0\u{1}capabilities\0\u{1}codecs\0\u{3}resource_limits\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.selectedProtocol) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.hostID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.hostName) }()
      case 4: try { try decoder.decodeRepeatedEnumField(value: &self.capabilities) }()
      case 5: try { try decoder.decodeRepeatedEnumField(value: &self.codecs) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._resourceLimits) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.selectedProtocol != 0 {
      try visitor.visitSingularUInt32Field(value: self.selectedProtocol, fieldNumber: 1)
    }
    if !self.hostID.isEmpty {
      try visitor.visitSingularStringField(value: self.hostID, fieldNumber: 2)
    }
    if !self.hostName.isEmpty {
      try visitor.visitSingularStringField(value: self.hostName, fieldNumber: 3)
    }
    if !self.capabilities.isEmpty {
      try visitor.visitPackedEnumField(value: self.capabilities, fieldNumber: 4)
    }
    if !self.codecs.isEmpty {
      try visitor.visitPackedEnumField(value: self.codecs, fieldNumber: 5)
    }
    try { if let v = self._resourceLimits {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSHostHello, rhs: VSHostHello) -> Bool {
    if lhs.selectedProtocol != rhs.selectedProtocol {return false}
    if lhs.hostID != rhs.hostID {return false}
    if lhs.hostName != rhs.hostName {return false}
    if lhs.capabilities != rhs.capabilities {return false}
    if lhs.codecs != rhs.codecs {return false}
    if lhs._resourceLimits != rhs._resourceLimits {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSSessionAccepted: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SessionAccepted"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0\u{3}session_epoch\0\u{3}heartbeat_interval_ms\0\u{3}negotiated_capabilities\0\u{3}negotiated_resource_limits\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.sessionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.sessionEpoch) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.heartbeatIntervalMs) }()
      case 4: try { try decoder.decodeRepeatedEnumField(value: &self.negotiatedCapabilities) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._negotiatedResourceLimits) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.sessionID.isEmpty {
      try visitor.visitSingularBytesField(value: self.sessionID, fieldNumber: 1)
    }
    if self.sessionEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionEpoch, fieldNumber: 2)
    }
    if self.heartbeatIntervalMs != 0 {
      try visitor.visitSingularUInt32Field(value: self.heartbeatIntervalMs, fieldNumber: 3)
    }
    if !self.negotiatedCapabilities.isEmpty {
      try visitor.visitPackedEnumField(value: self.negotiatedCapabilities, fieldNumber: 4)
    }
    try { if let v = self._negotiatedResourceLimits {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSSessionAccepted, rhs: VSSessionAccepted) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.sessionEpoch != rhs.sessionEpoch {return false}
    if lhs.heartbeatIntervalMs != rhs.heartbeatIntervalMs {return false}
    if lhs.negotiatedCapabilities != rhs.negotiatedCapabilities {return false}
    if lhs._negotiatedResourceLimits != rhs._negotiatedResourceLimits {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSSessionRejected: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SessionRejected"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}reason_code\0\u{1}message\0\u{1}retryable\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.retryable) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.retryable != false {
      try visitor.visitSingularBoolField(value: self.retryable, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSSessionRejected, rhs: VSSessionRejected) -> Bool {
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.message != rhs.message {return false}
    if lhs.retryable != rhs.retryable {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSPing: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Ping"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sequence\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.sequence) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sequence != 0 {
      try visitor.visitSingularUInt64Field(value: self.sequence, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSPing, rhs: VSPing) -> Bool {
    if lhs.sequence != rhs.sequence {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSPong: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Pong"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sequence\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.sequence) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sequence != 0 {
      try visitor.visitSingularUInt64Field(value: self.sequence, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSPong, rhs: VSPong) -> Bool {
    if lhs.sequence != rhs.sequence {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSResumeSessionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResumeSessionRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0\u{3}previous_session_epoch\0\u{3}last_received_message_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.sessionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.previousSessionEpoch) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.lastReceivedMessageID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sessionID.isEmpty {
      try visitor.visitSingularBytesField(value: self.sessionID, fieldNumber: 1)
    }
    if self.previousSessionEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.previousSessionEpoch, fieldNumber: 2)
    }
    if self.lastReceivedMessageID != 0 {
      try visitor.visitSingularUInt64Field(value: self.lastReceivedMessageID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSResumeSessionRequest, rhs: VSResumeSessionRequest) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.previousSessionEpoch != rhs.previousSessionEpoch {return false}
    if lhs.lastReceivedMessageID != rhs.lastReceivedMessageID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSResumeSessionResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResumeSessionResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}accepted\0\u{3}session_epoch\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.sessionEpoch) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 1)
    }
    if self.sessionEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionEpoch, fieldNumber: 2)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSResumeSessionResult, rhs: VSResumeSessionResult) -> Bool {
    if lhs.accepted != rhs.accepted {return false}
    if lhs.sessionEpoch != rhs.sessionEpoch {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSDisconnectNotice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DisconnectNotice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}reason_code\0\u{3}may_resume\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.mayResume) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 1)
    }
    if self.mayResume != false {
      try visitor.visitSingularBoolField(value: self.mayResume, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSDisconnectNotice, rhs: VSDisconnectNotice) -> Bool {
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.mayResume != rhs.mayResume {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
