// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/advanced.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum VSColorPrimaries: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case bt709 // = 1
  case displayP3 // = 2
  case bt2020 // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .bt709
    case 2: self = .displayP3
    case 3: self = .bt2020
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .bt709: return 1
    case .displayP3: return 2
    case .bt2020: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSColorPrimaries] = [
    .unspecified,
    .bt709,
    .displayP3,
    .bt2020,
  ]

}

public enum VSTransferFunction: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case srgb // = 1
  case bt709 // = 2
  case pq // = 3
  case hlg // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .srgb
    case 2: self = .bt709
    case 3: self = .pq
    case 4: self = .hlg
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .srgb: return 1
    case .bt709: return 2
    case .pq: return 3
    case .hlg: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSTransferFunction] = [
    .unspecified,
    .srgb,
    .bt709,
    .pq,
    .hlg,
  ]

}

public enum VSMatrixCoefficients: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case bt709 // = 1
  case bt2020NonConstant // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .bt709
    case 2: self = .bt2020NonConstant
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .bt709: return 1
    case .bt2020NonConstant: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSMatrixCoefficients] = [
    .unspecified,
    .bt709,
    .bt2020NonConstant,
  ]

}

public enum VSAudioCodec: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case pcmS16Le // = 1
  case aacLc // = 2
  case opus // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .pcmS16Le
    case 2: self = .aacLc
    case 3: self = .opus
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .pcmS16Le: return 1
    case .aacLc: return 2
    case .opus: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSAudioCodec] = [
    .unspecified,
    .pcmS16Le,
    .aacLc,
    .opus,
  ]

}

public struct VSResourceLimits: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var maximumClients: UInt32 = 0

  public var maximumDisplays: UInt32 = 0

  public var maximumVideoStreams: UInt32 = 0

  public var maximumAudioStreams: UInt32 = 0

  public var maximumClipboardBytes: UInt64 = 0

  public var maximumFileBytes: UInt64 = 0

  public var maximumFileChunkBytes: UInt32 = 0

  public var maximumEncryptedMediaRecordBytes: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSColorDescription: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var primaries: VSColorPrimaries = .unspecified

  public var transferFunction: VSTransferFunction = .unspecified

  public var matrixCoefficients: VSMatrixCoefficients = .unspecified

  public var fullRange: Bool = false

  public var bitDepth: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSVideoDecodeCapability: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var codec: VSCodec = .unspecified

  public var maximumWidth: UInt32 = 0

  public var maximumHeight: UInt32 = 0

  public var maximumFramesPerSecond: UInt32 = 0

  public var bitDepths: [UInt32] = []

  public var transferFunctions: [VSTransferFunction] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSInputTarget: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var displayID: String = String()

  public var streamID: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSAudioConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt64 = 0

  public var configEpoch: UInt64 = 0

  public var codec: VSAudioCodec = .unspecified

  public var sampleRateHz: UInt32 = 0

  public var channelCount: UInt32 = 0

  public var framesPerPacket: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSAudioConfigResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt64 = 0

  public var configEpoch: UInt64 = 0

  public var accepted: Bool = false

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSAudioPacketHeader: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt64 = 0

  public var sessionEpoch: UInt64 = 0

  public var configEpoch: UInt64 = 0

  public var sequence: UInt64 = 0

  public var frameCount: UInt32 = 0

  public var payloadLength: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSClipboardOffer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var changeID: Data = Data()

  public var originDeviceID: String = String()

  public var mimeType: String = String()

  public var byteLength: UInt64 = 0

  public var sha256: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSClipboardRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var changeID: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSClipboardContent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var changeID: Data = Data()

  public var originDeviceID: String = String()

  public var mimeType: String = String()

  public var content: Data = Data()

  public var sha256: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSFileOffer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var transferID: Data = Data()

  public var fileName: String = String()

  public var mimeType: String = String()

  public var byteLength: UInt64 = 0

  public var sha256: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSFileAccept: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var transferID: Data = Data()

  public var accepted: Bool = false

  public var maximumChunkBytes: UInt32 = 0

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSFileChunkHeader: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var transferID: Data = Data()

  public var offset: UInt64 = 0

  public var payloadLength: UInt32 = 0

  public var sessionEpoch: UInt64 = 0

  public var chunkSha256: Data = Data()

  public var final: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSFileTransferProgress: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var transferID: Data = Data()

  public var receivedBytes: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSFileTransferCancel: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var transferID: Data = Data()

  public var reasonCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSFileTransferComplete: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var transferID: Data = Data()

  public var accepted: Bool = false

  public var sha256: Data = Data()

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSHostActionDescriptor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var actionID: String = String()

  public var localizedName: String = String()

  public var requiresConfirmation: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSHostActionCatalog: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var actions: [VSHostActionDescriptor] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSHostActionInvoke: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var actionID: String = String()

  public var invocationID: Data = Data()

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _target: VSInputTarget? = nil
}

public struct VSHostActionResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var invocationID: Data = Data()

  public var accepted: Bool = false

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSWakeHostRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: Data = Data()

  public var targetMacAddress: Data = Data()

  public var secureOnPassword: Data = Data()

  public var hostID: String = String()

  public var deviceID: String = String()

  public var keyID: String = String()

  public var issuedAtUnixSeconds: UInt64 = 0

  public var expiresAtUnixSeconds: UInt64 = 0

  public var nonce: Data = Data()

  public var signature: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSWakeHostResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: Data = Data()

  public var accepted: Bool = false

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSManagedPolicyStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var managed: Bool = false

  public var clipboardAllowed: Bool = false

  public var fileTransferAllowed: Bool = false

  public var audioAllowed: Bool = false

  public var wakeAllowed: Bool = false

  public var maximumFileBytes: UInt64 = 0

  public var customGesturesAllowed: Bool = false

  public var hostActionsAllowed: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSColorPrimaries: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COLOR_PRIMARIES_UNSPECIFIED\0\u{1}COLOR_PRIMARIES_BT709\0\u{1}COLOR_PRIMARIES_DISPLAY_P3\0\u{1}COLOR_PRIMARIES_BT2020\0")
}

extension VSTransferFunction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TRANSFER_FUNCTION_UNSPECIFIED\0\u{1}TRANSFER_FUNCTION_SRGB\0\u{1}TRANSFER_FUNCTION_BT709\0\u{1}TRANSFER_FUNCTION_PQ\0\u{1}TRANSFER_FUNCTION_HLG\0")
}

extension VSMatrixCoefficients: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MATRIX_COEFFICIENTS_UNSPECIFIED\0\u{1}MATRIX_COEFFICIENTS_BT709\0\u{1}MATRIX_COEFFICIENTS_BT2020_NON_CONSTANT\0")
}

extension VSAudioCodec: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AUDIO_CODEC_UNSPECIFIED\0\u{1}AUDIO_CODEC_PCM_S16LE\0\u{1}AUDIO_CODEC_AAC_LC\0\u{1}AUDIO_CODEC_OPUS\0")
}

extension VSResourceLimits: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResourceLimits"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}maximum_clients\0\u{3}maximum_displays\0\u{3}maximum_video_streams\0\u{3}maximum_audio_streams\0\u{3}maximum_clipboard_bytes\0\u{3}maximum_file_bytes\0\u{3}maximum_file_chunk_bytes\0\u{3}maximum_encrypted_media_record_bytes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.maximumClients) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.maximumDisplays) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.maximumVideoStreams) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.maximumAudioStreams) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.maximumClipboardBytes) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.maximumFileBytes) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.maximumFileChunkBytes) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.maximumEncryptedMediaRecordBytes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.maximumClients != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumClients, fieldNumber: 1)
    }
    if self.maximumDisplays != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumDisplays, fieldNumber: 2)
    }
    if self.maximumVideoStreams != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumVideoStreams, fieldNumber: 3)
    }
    if self.maximumAudioStreams != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumAudioStreams, fieldNumber: 4)
    }
    if self.maximumClipboardBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.maximumClipboardBytes, fieldNumber: 5)
    }
    if self.maximumFileBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.maximumFileBytes, fieldNumber: 6)
    }
    if self.maximumFileChunkBytes != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumFileChunkBytes, fieldNumber: 7)
    }
    if self.maximumEncryptedMediaRecordBytes != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumEncryptedMediaRecordBytes, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSResourceLimits, rhs: VSResourceLimits) -> Bool {
    if lhs.maximumClients != rhs.maximumClients {return false}
    if lhs.maximumDisplays != rhs.maximumDisplays {return false}
    if lhs.maximumVideoStreams != rhs.maximumVideoStreams {return false}
    if lhs.maximumAudioStreams != rhs.maximumAudioStreams {return false}
    if lhs.maximumClipboardBytes != rhs.maximumClipboardBytes {return false}
    if lhs.maximumFileBytes != rhs.maximumFileBytes {return false}
    if lhs.maximumFileChunkBytes != rhs.maximumFileChunkBytes {return false}
    if lhs.maximumEncryptedMediaRecordBytes != rhs.maximumEncryptedMediaRecordBytes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSColorDescription: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ColorDescription"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}primaries\0\u{3}transfer_function\0\u{3}matrix_coefficients\0\u{3}full_range\0\u{3}bit_depth\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.primaries) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.transferFunction) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.matrixCoefficients) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.fullRange) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.bitDepth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.primaries != .unspecified {
      try visitor.visitSingularEnumField(value: self.primaries, fieldNumber: 1)
    }
    if self.transferFunction != .unspecified {
      try visitor.visitSingularEnumField(value: self.transferFunction, fieldNumber: 2)
    }
    if self.matrixCoefficients != .unspecified {
      try visitor.visitSingularEnumField(value: self.matrixCoefficients, fieldNumber: 3)
    }
    if self.fullRange != false {
      try visitor.visitSingularBoolField(value: self.fullRange, fieldNumber: 4)
    }
    if self.bitDepth != 0 {
      try visitor.visitSingularUInt32Field(value: self.bitDepth, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSColorDescription, rhs: VSColorDescription) -> Bool {
    if lhs.primaries != rhs.primaries {return false}
    if lhs.transferFunction != rhs.transferFunction {return false}
    if lhs.matrixCoefficients != rhs.matrixCoefficients {return false}
    if lhs.fullRange != rhs.fullRange {return false}
    if lhs.bitDepth != rhs.bitDepth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSVideoDecodeCapability: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoDecodeCapability"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}codec\0\u{3}maximum_width\0\u{3}maximum_height\0\u{3}maximum_frames_per_second\0\u{3}bit_depths\0\u{3}transfer_functions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.codec) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.maximumWidth) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.maximumHeight) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.maximumFramesPerSecond) }()
      case 5: try { try decoder.decodeRepeatedUInt32Field(value: &self.bitDepths) }()
      case 6: try { try decoder.decodeRepeatedEnumField(value: &self.transferFunctions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.codec != .unspecified {
      try visitor.visitSingularEnumField(value: self.codec, fieldNumber: 1)
    }
    if self.maximumWidth != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumWidth, fieldNumber: 2)
    }
    if self.maximumHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumHeight, fieldNumber: 3)
    }
    if self.maximumFramesPerSecond != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumFramesPerSecond, fieldNumber: 4)
    }
    if !self.bitDepths.isEmpty {
      try visitor.visitPackedUInt32Field(value: self.bitDepths, fieldNumber: 5)
    }
    if !self.transferFunctions.isEmpty {
      try visitor.visitPackedEnumField(value: self.transferFunctions, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSVideoDecodeCapability, rhs: VSVideoDecodeCapability) -> Bool {
    if lhs.codec != rhs.codec {return false}
    if lhs.maximumWidth != rhs.maximumWidth {return false}
    if lhs.maximumHeight != rhs.maximumHeight {return false}
    if lhs.maximumFramesPerSecond != rhs.maximumFramesPerSecond {return false}
    if lhs.bitDepths != rhs.bitDepths {return false}
    if lhs.transferFunctions != rhs.transferFunctions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSInputTarget: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputTarget"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}display_id\0\u{3}stream_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.displayID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.displayID.isEmpty {
      try visitor.visitSingularStringField(value: self.displayID, fieldNumber: 1)
    }
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSInputTarget, rhs: VSInputTarget) -> Bool {
    if lhs.displayID != rhs.displayID {return false}
    if lhs.streamID != rhs.streamID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSAudioConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AudioConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}config_epoch\0\u{1}codec\0\u{3}sample_rate_hz\0\u{3}channel_count\0\u{3}frames_per_packet\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.configEpoch) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.codec) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.sampleRateHz) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.channelCount) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.framesPerPacket) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 1)
    }
    if self.configEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.configEpoch, fieldNumber: 2)
    }
    if self.codec != .unspecified {
      try visitor.visitSingularEnumField(value: self.codec, fieldNumber: 3)
    }
    if self.sampleRateHz != 0 {
      try visitor.visitSingularUInt32Field(value: self.sampleRateHz, fieldNumber: 4)
    }
    if self.channelCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.channelCount, fieldNumber: 5)
    }
    if self.framesPerPacket != 0 {
      try visitor.visitSingularUInt32Field(value: self.framesPerPacket, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSAudioConfig, rhs: VSAudioConfig) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.configEpoch != rhs.configEpoch {return false}
    if lhs.codec != rhs.codec {return false}
    if lhs.sampleRateHz != rhs.sampleRateHz {return false}
    if lhs.channelCount != rhs.channelCount {return false}
    if lhs.framesPerPacket != rhs.framesPerPacket {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSAudioConfigResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AudioConfigResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}config_epoch\0\u{1}accepted\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.configEpoch) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 1)
    }
    if self.configEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.configEpoch, fieldNumber: 2)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 3)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSAudioConfigResult, rhs: VSAudioConfigResult) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.configEpoch != rhs.configEpoch {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSAudioPacketHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AudioPacketHeader"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}session_epoch\0\u{3}config_epoch\0\u{1}sequence\0\u{3}frame_count\0\u{3}payload_length\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.sessionEpoch) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.configEpoch) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.sequence) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.frameCount) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.payloadLength) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 1)
    }
    if self.sessionEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionEpoch, fieldNumber: 2)
    }
    if self.configEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.configEpoch, fieldNumber: 3)
    }
    if self.sequence != 0 {
      try visitor.visitSingularUInt64Field(value: self.sequence, fieldNumber: 4)
    }
    if self.frameCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameCount, fieldNumber: 5)
    }
    if self.payloadLength != 0 {
      try visitor.visitSingularUInt32Field(value: self.payloadLength, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSAudioPacketHeader, rhs: VSAudioPacketHeader) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.sessionEpoch != rhs.sessionEpoch {return false}
    if lhs.configEpoch != rhs.configEpoch {return false}
    if lhs.sequence != rhs.sequence {return false}
    if lhs.frameCount != rhs.frameCount {return false}
    if lhs.payloadLength != rhs.payloadLength {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSClipboardOffer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClipboardOffer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}change_id\0\u{3}origin_device_id\0\u{3}mime_type\0\u{3}byte_length\0\u{1}sha256\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.changeID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.originDeviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.mimeType) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.byteLength) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.sha256) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.changeID.isEmpty {
      try visitor.visitSingularBytesField(value: self.changeID, fieldNumber: 1)
    }
    if !self.originDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.originDeviceID, fieldNumber: 2)
    }
    if !self.mimeType.isEmpty {
      try visitor.visitSingularStringField(value: self.mimeType, fieldNumber: 3)
    }
    if self.byteLength != 0 {
      try visitor.visitSingularUInt64Field(value: self.byteLength, fieldNumber: 4)
    }
    if !self.sha256.isEmpty {
      try visitor.visitSingularBytesField(value: self.sha256, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSClipboardOffer, rhs: VSClipboardOffer) -> Bool {
    if lhs.changeID != rhs.changeID {return false}
    if lhs.originDeviceID != rhs.originDeviceID {return false}
    if lhs.mimeType != rhs.mimeType {return false}
    if lhs.byteLength != rhs.byteLength {return false}
    if lhs.sha256 != rhs.sha256 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSClipboardRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClipboardRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}change_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.changeID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.changeID.isEmpty {
      try visitor.visitSingularBytesField(value: self.changeID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSClipboardRequest, rhs: VSClipboardRequest) -> Bool {
    if lhs.changeID != rhs.changeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSClipboardContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClipboardContent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}change_id\0\u{3}origin_device_id\0\u{3}mime_type\0\u{1}content\0\u{1}sha256\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.changeID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.originDeviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.mimeType) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.content) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.sha256) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.changeID.isEmpty {
      try visitor.visitSingularBytesField(value: self.changeID, fieldNumber: 1)
    }
    if !self.originDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.originDeviceID, fieldNumber: 2)
    }
    if !self.mimeType.isEmpty {
      try visitor.visitSingularStringField(value: self.mimeType, fieldNumber: 3)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularBytesField(value: self.content, fieldNumber: 4)
    }
    if !self.sha256.isEmpty {
      try visitor.visitSingularBytesField(value: self.sha256, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSClipboardContent, rhs: VSClipboardContent) -> Bool {
    if lhs.changeID != rhs.changeID {return false}
    if lhs.originDeviceID != rhs.originDeviceID {return false}
    if lhs.mimeType != rhs.mimeType {return false}
    if lhs.content != rhs.content {return false}
    if lhs.sha256 != rhs.sha256 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSFileOffer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileOffer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}transfer_id\0\u{3}file_name\0\u{3}mime_type\0\u{3}byte_length\0\u{1}sha256\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.transferID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fileName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.mimeType) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.byteLength) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.sha256) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.transferID.isEmpty {
      try visitor.visitSingularBytesField(value: self.transferID, fieldNumber: 1)
    }
    if !self.fileName.isEmpty {
      try visitor.visitSingularStringField(value: self.fileName, fieldNumber: 2)
    }
    if !self.mimeType.isEmpty {
      try visitor.visitSingularStringField(value: self.mimeType, fieldNumber: 3)
    }
    if self.byteLength != 0 {
      try visitor.visitSingularUInt64Field(value: self.byteLength, fieldNumber: 4)
    }
    if !self.sha256.isEmpty {
      try visitor.visitSingularBytesField(value: self.sha256, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSFileOffer, rhs: VSFileOffer) -> Bool {
    if lhs.transferID != rhs.transferID {return false}
    if lhs.fileName != rhs.fileName {return false}
    if lhs.mimeType != rhs.mimeType {return false}
    if lhs.byteLength != rhs.byteLength {return false}
    if lhs.sha256 != rhs.sha256 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSFileAccept: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileAccept"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}transfer_id\0\u{1}accepted\0\u{3}maximum_chunk_bytes\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.transferID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.maximumChunkBytes) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.transferID.isEmpty {
      try visitor.visitSingularBytesField(value: self.transferID, fieldNumber: 1)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 2)
    }
    if self.maximumChunkBytes != 0 {
      try visitor.visitSingularUInt32Field(value: self.maximumChunkBytes, fieldNumber: 3)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSFileAccept, rhs: VSFileAccept) -> Bool {
    if lhs.transferID != rhs.transferID {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.maximumChunkBytes != rhs.maximumChunkBytes {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSFileChunkHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileChunkHeader"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}transfer_id\0\u{1}offset\0\u{3}payload_length\0\u{3}session_epoch\0\u{3}chunk_sha256\0\u{1}final\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.transferID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.offset) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.payloadLength) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.sessionEpoch) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.chunkSha256) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.final) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.transferID.isEmpty {
      try visitor.visitSingularBytesField(value: self.transferID, fieldNumber: 1)
    }
    if self.offset != 0 {
      try visitor.visitSingularUInt64Field(value: self.offset, fieldNumber: 2)
    }
    if self.payloadLength != 0 {
      try visitor.visitSingularUInt32Field(value: self.payloadLength, fieldNumber: 3)
    }
    if self.sessionEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionEpoch, fieldNumber: 4)
    }
    if !self.chunkSha256.isEmpty {
      try visitor.visitSingularBytesField(value: self.chunkSha256, fieldNumber: 5)
    }
    if self.final != false {
      try visitor.visitSingularBoolField(value: self.final, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSFileChunkHeader, rhs: VSFileChunkHeader) -> Bool {
    if lhs.transferID != rhs.transferID {return false}
    if lhs.offset != rhs.offset {return false}
    if lhs.payloadLength != rhs.payloadLength {return false}
    if lhs.sessionEpoch != rhs.sessionEpoch {return false}
    if lhs.chunkSha256 != rhs.chunkSha256 {return false}
    if lhs.final != rhs.final {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSFileTransferProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileTransferProgress"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}transfer_id\0\u{3}received_bytes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.transferID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.receivedBytes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.transferID.isEmpty {
      try visitor.visitSingularBytesField(value: self.transferID, fieldNumber: 1)
    }
    if self.receivedBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.receivedBytes, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSFileTransferProgress, rhs: VSFileTransferProgress) -> Bool {
    if lhs.transferID != rhs.transferID {return false}
    if lhs.receivedBytes != rhs.receivedBytes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSFileTransferCancel: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileTransferCancel"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}transfer_id\0\u{3}reason_code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.transferID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.transferID.isEmpty {
      try visitor.visitSingularBytesField(value: self.transferID, fieldNumber: 1)
    }
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSFileTransferCancel, rhs: VSFileTransferCancel) -> Bool {
    if lhs.transferID != rhs.transferID {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSFileTransferComplete: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileTransferComplete"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}transfer_id\0\u{1}accepted\0\u{1}sha256\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.transferID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.sha256) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.transferID.isEmpty {
      try visitor.visitSingularBytesField(value: self.transferID, fieldNumber: 1)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 2)
    }
    if !self.sha256.isEmpty {
      try visitor.visitSingularBytesField(value: self.sha256, fieldNumber: 3)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSFileTransferComplete, rhs: VSFileTransferComplete) -> Bool {
    if lhs.transferID != rhs.transferID {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.sha256 != rhs.sha256 {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSHostActionDescriptor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostActionDescriptor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}action_id\0\u{3}localized_name\0\u{3}requires_confirmation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.actionID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.localizedName) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.requiresConfirmation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.actionID.isEmpty {
      try visitor.visitSingularStringField(value: self.actionID, fieldNumber: 1)
    }
    if !self.localizedName.isEmpty {
      try visitor.visitSingularStringField(value: self.localizedName, fieldNumber: 2)
    }
    if self.requiresConfirmation != false {
      try visitor.visitSingularBoolField(value: self.requiresConfirmation, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSHostActionDescriptor, rhs: VSHostActionDescriptor) -> Bool {
    if lhs.actionID != rhs.actionID {return false}
    if lhs.localizedName != rhs.localizedName {return false}
    if lhs.requiresConfirmation != rhs.requiresConfirmation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSHostActionCatalog: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostActionCatalog"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}actions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.actions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.actions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.actions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSHostActionCatalog, rhs: VSHostActionCatalog) -> Bool {
    if lhs.actions != rhs.actions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSHostActionInvoke: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostActionInvoke"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}action_id\0\u{3}invocation_id\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.actionID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.invocationID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.actionID.isEmpty {
      try visitor.visitSingularStringField(value: self.actionID, fieldNumber: 1)
    }
    if !self.invocationID.isEmpty {
      try visitor.visitSingularBytesField(value: self.invocationID, fieldNumber: 2)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSHostActionInvoke, rhs: VSHostActionInvoke) -> Bool {
    if lhs.actionID != rhs.actionID {return false}
    if lhs.invocationID != rhs.invocationID {return false}
    if lhs._target != rhs._target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSHostActionResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostActionResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}invocation_id\0\u{1}accepted\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.invocationID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.invocationID.isEmpty {
      try visitor.visitSingularBytesField(value: self.invocationID, fieldNumber: 1)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 2)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSHostActionResult, rhs: VSHostActionResult) -> Bool {
    if lhs.invocationID != rhs.invocationID {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSWakeHostRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WakeHostRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{3}target_mac_address\0\u{3}secure_on_password\0\u{3}host_id\0\u{3}device_id\0\u{3}key_id\0\u{3}issued_at_unix_seconds\0\u{3}expires_at_unix_seconds\0\u{1}nonce\0\u{1}signature\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.targetMacAddress) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.secureOnPassword) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.hostID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.keyID) }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self.issuedAtUnixSeconds) }()
      case 8: try { try decoder.decodeSingularUInt64Field(value: &self.expiresAtUnixSeconds) }()
      case 9: try { try decoder.decodeSingularBytesField(value: &self.nonce) }()
      case 10: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularBytesField(value: self.requestID, fieldNumber: 1)
    }
    if !self.targetMacAddress.isEmpty {
      try visitor.visitSingularBytesField(value: self.targetMacAddress, fieldNumber: 2)
    }
    if !self.secureOnPassword.isEmpty {
      try visitor.visitSingularBytesField(value: self.secureOnPassword, fieldNumber: 3)
    }
    if !self.hostID.isEmpty {
      try visitor.visitSingularStringField(value: self.hostID, fieldNumber: 4)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 5)
    }
    if !self.keyID.isEmpty {
      try visitor.visitSingularStringField(value: self.keyID, fieldNumber: 6)
    }
    if self.issuedAtUnixSeconds != 0 {
      try visitor.visitSingularUInt64Field(value: self.issuedAtUnixSeconds, fieldNumber: 7)
    }
    if self.expiresAtUnixSeconds != 0 {
      try visitor.visitSingularUInt64Field(value: self.expiresAtUnixSeconds, fieldNumber: 8)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.nonce, fieldNumber: 9)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSWakeHostRequest, rhs: VSWakeHostRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.targetMacAddress != rhs.targetMacAddress {return false}
    if lhs.secureOnPassword != rhs.secureOnPassword {return false}
    if lhs.hostID != rhs.hostID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.issuedAtUnixSeconds != rhs.issuedAtUnixSeconds {return false}
    if lhs.expiresAtUnixSeconds != rhs.expiresAtUnixSeconds {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSWakeHostResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WakeHostResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}accepted\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularBytesField(value: self.requestID, fieldNumber: 1)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 2)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSWakeHostResult, rhs: VSWakeHostResult) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSManagedPolicyStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ManagedPolicyStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}managed\0\u{3}clipboard_allowed\0\u{3}file_transfer_allowed\0\u{3}audio_allowed\0\u{3}wake_allowed\0\u{3}maximum_file_bytes\0\u{3}custom_gestures_allowed\0\u{3}host_actions_allowed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.managed) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.clipboardAllowed) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.fileTransferAllowed) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.audioAllowed) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.wakeAllowed) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.maximumFileBytes) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.customGesturesAllowed) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.hostActionsAllowed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.managed != false {
      try visitor.visitSingularBoolField(value: self.managed, fieldNumber: 1)
    }
    if self.clipboardAllowed != false {
      try visitor.visitSingularBoolField(value: self.clipboardAllowed, fieldNumber: 2)
    }
    if self.fileTransferAllowed != false {
      try visitor.visitSingularBoolField(value: self.fileTransferAllowed, fieldNumber: 3)
    }
    if self.audioAllowed != false {
      try visitor.visitSingularBoolField(value: self.audioAllowed, fieldNumber: 4)
    }
    if self.wakeAllowed != false {
      try visitor.visitSingularBoolField(value: self.wakeAllowed, fieldNumber: 5)
    }
    if self.maximumFileBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.maximumFileBytes, fieldNumber: 6)
    }
    if self.customGesturesAllowed != false {
      try visitor.visitSingularBoolField(value: self.customGesturesAllowed, fieldNumber: 7)
    }
    if self.hostActionsAllowed != false {
      try visitor.visitSingularBoolField(value: self.hostActionsAllowed, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSManagedPolicyStatus, rhs: VSManagedPolicyStatus) -> Bool {
    if lhs.managed != rhs.managed {return false}
    if lhs.clipboardAllowed != rhs.clipboardAllowed {return false}
    if lhs.fileTransferAllowed != rhs.fileTransferAllowed {return false}
    if lhs.audioAllowed != rhs.audioAllowed {return false}
    if lhs.wakeAllowed != rhs.wakeAllowed {return false}
    if lhs.maximumFileBytes != rhs.maximumFileBytes {return false}
    if lhs.customGesturesAllowed != rhs.customGesturesAllowed {return false}
    if lhs.hostActionsAllowed != rhs.hostActionsAllowed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
