// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/envelope.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct VSEnvelope: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var protocolVersion: UInt32 {
    get {return _storage._protocolVersion}
    set {_uniqueStorage()._protocolVersion = newValue}
  }

  public var messageID: UInt64 {
    get {return _storage._messageID}
    set {_uniqueStorage()._messageID = newValue}
  }

  public var correlationID: UInt64 {
    get {return _storage._correlationID}
    set {_uniqueStorage()._correlationID = newValue}
  }

  public var sessionID: Data {
    get {return _storage._sessionID}
    set {_uniqueStorage()._sessionID = newValue}
  }

  public var sessionEpoch: UInt64 {
    get {return _storage._sessionEpoch}
    set {_uniqueStorage()._sessionEpoch = newValue}
  }

  public var sentAtMonotonicNs: UInt64 {
    get {return _storage._sentAtMonotonicNs}
    set {_uniqueStorage()._sentAtMonotonicNs = newValue}
  }

  public var payload: OneOf_Payload? {
    get {return _storage._payload}
    set {_uniqueStorage()._payload = newValue}
  }

  public var clientHello: VSClientHello {
    get {
      if case .clientHello(let v)? = _storage._payload {return v}
      return VSClientHello()
    }
    set {_uniqueStorage()._payload = .clientHello(newValue)}
  }

  public var hostHello: VSHostHello {
    get {
      if case .hostHello(let v)? = _storage._payload {return v}
      return VSHostHello()
    }
    set {_uniqueStorage()._payload = .hostHello(newValue)}
  }

  public var sessionAccepted: VSSessionAccepted {
    get {
      if case .sessionAccepted(let v)? = _storage._payload {return v}
      return VSSessionAccepted()
    }
    set {_uniqueStorage()._payload = .sessionAccepted(newValue)}
  }

  public var sessionRejected: VSSessionRejected {
    get {
      if case .sessionRejected(let v)? = _storage._payload {return v}
      return VSSessionRejected()
    }
    set {_uniqueStorage()._payload = .sessionRejected(newValue)}
  }

  public var ping: VSPing {
    get {
      if case .ping(let v)? = _storage._payload {return v}
      return VSPing()
    }
    set {_uniqueStorage()._payload = .ping(newValue)}
  }

  public var pong: VSPong {
    get {
      if case .pong(let v)? = _storage._payload {return v}
      return VSPong()
    }
    set {_uniqueStorage()._payload = .pong(newValue)}
  }

  public var resumeSessionRequest: VSResumeSessionRequest {
    get {
      if case .resumeSessionRequest(let v)? = _storage._payload {return v}
      return VSResumeSessionRequest()
    }
    set {_uniqueStorage()._payload = .resumeSessionRequest(newValue)}
  }

  public var resumeSessionResult: VSResumeSessionResult {
    get {
      if case .resumeSessionResult(let v)? = _storage._payload {return v}
      return VSResumeSessionResult()
    }
    set {_uniqueStorage()._payload = .resumeSessionResult(newValue)}
  }

  public var disconnectNotice: VSDisconnectNotice {
    get {
      if case .disconnectNotice(let v)? = _storage._payload {return v}
      return VSDisconnectNotice()
    }
    set {_uniqueStorage()._payload = .disconnectNotice(newValue)}
  }

  public var pairingOffer: VSPairingOffer {
    get {
      if case .pairingOffer(let v)? = _storage._payload {return v}
      return VSPairingOffer()
    }
    set {_uniqueStorage()._payload = .pairingOffer(newValue)}
  }

  public var pairingRequest: VSPairingRequest {
    get {
      if case .pairingRequest(let v)? = _storage._payload {return v}
      return VSPairingRequest()
    }
    set {_uniqueStorage()._payload = .pairingRequest(newValue)}
  }

  public var pairingResult: VSPairingResult {
    get {
      if case .pairingResult(let v)? = _storage._payload {return v}
      return VSPairingResult()
    }
    set {_uniqueStorage()._payload = .pairingResult(newValue)}
  }

  public var deviceRevoked: VSDeviceRevoked {
    get {
      if case .deviceRevoked(let v)? = _storage._payload {return v}
      return VSDeviceRevoked()
    }
    set {_uniqueStorage()._payload = .deviceRevoked(newValue)}
  }

  public var keyRotationRequest: VSKeyRotationRequest {
    get {
      if case .keyRotationRequest(let v)? = _storage._payload {return v}
      return VSKeyRotationRequest()
    }
    set {_uniqueStorage()._payload = .keyRotationRequest(newValue)}
  }

  public var keyRotationResult: VSKeyRotationResult {
    get {
      if case .keyRotationResult(let v)? = _storage._payload {return v}
      return VSKeyRotationResult()
    }
    set {_uniqueStorage()._payload = .keyRotationResult(newValue)}
  }

  public var deviceRevocation: VSDeviceRevocation {
    get {
      if case .deviceRevocation(let v)? = _storage._payload {return v}
      return VSDeviceRevocation()
    }
    set {_uniqueStorage()._payload = .deviceRevocation(newValue)}
  }

  public var trafficKeyUpdate: VSTrafficKeyUpdate {
    get {
      if case .trafficKeyUpdate(let v)? = _storage._payload {return v}
      return VSTrafficKeyUpdate()
    }
    set {_uniqueStorage()._payload = .trafficKeyUpdate(newValue)}
  }

  public var trafficKeyAck: VSTrafficKeyAck {
    get {
      if case .trafficKeyAck(let v)? = _storage._payload {return v}
      return VSTrafficKeyAck()
    }
    set {_uniqueStorage()._payload = .trafficKeyAck(newValue)}
  }

  public var listDisplaysRequest: VSListDisplaysRequest {
    get {
      if case .listDisplaysRequest(let v)? = _storage._payload {return v}
      return VSListDisplaysRequest()
    }
    set {_uniqueStorage()._payload = .listDisplaysRequest(newValue)}
  }

  public var listDisplaysResponse: VSListDisplaysResponse {
    get {
      if case .listDisplaysResponse(let v)? = _storage._payload {return v}
      return VSListDisplaysResponse()
    }
    set {_uniqueStorage()._payload = .listDisplaysResponse(newValue)}
  }

  public var startDisplayRequest: VSStartDisplayRequest {
    get {
      if case .startDisplayRequest(let v)? = _storage._payload {return v}
      return VSStartDisplayRequest()
    }
    set {_uniqueStorage()._payload = .startDisplayRequest(newValue)}
  }

  public var startDisplayResponse: VSStartDisplayResponse {
    get {
      if case .startDisplayResponse(let v)? = _storage._payload {return v}
      return VSStartDisplayResponse()
    }
    set {_uniqueStorage()._payload = .startDisplayResponse(newValue)}
  }

  public var stopDisplay: VSStopDisplay {
    get {
      if case .stopDisplay(let v)? = _storage._payload {return v}
      return VSStopDisplay()
    }
    set {_uniqueStorage()._payload = .stopDisplay(newValue)}
  }

  public var displayChanged: VSDisplayChanged {
    get {
      if case .displayChanged(let v)? = _storage._payload {return v}
      return VSDisplayChanged()
    }
    set {_uniqueStorage()._payload = .displayChanged(newValue)}
  }

  public var videoConfig: VSVideoConfig {
    get {
      if case .videoConfig(let v)? = _storage._payload {return v}
      return VSVideoConfig()
    }
    set {_uniqueStorage()._payload = .videoConfig(newValue)}
  }

  public var videoConfigResult: VSVideoConfigResult {
    get {
      if case .videoConfigResult(let v)? = _storage._payload {return v}
      return VSVideoConfigResult()
    }
    set {_uniqueStorage()._payload = .videoConfigResult(newValue)}
  }

  public var requestKeyframe: VSRequestKeyframe {
    get {
      if case .requestKeyframe(let v)? = _storage._payload {return v}
      return VSRequestKeyframe()
    }
    set {_uniqueStorage()._payload = .requestKeyframe(newValue)}
  }

  public var videoStreamEnded: VSVideoStreamEnded {
    get {
      if case .videoStreamEnded(let v)? = _storage._payload {return v}
      return VSVideoStreamEnded()
    }
    set {_uniqueStorage()._payload = .videoStreamEnded(newValue)}
  }

  public var touchEvent: VSTouchEvent {
    get {
      if case .touchEvent(let v)? = _storage._payload {return v}
      return VSTouchEvent()
    }
    set {_uniqueStorage()._payload = .touchEvent(newValue)}
  }

  public var pointerEvent: VSPointerEvent {
    get {
      if case .pointerEvent(let v)? = _storage._payload {return v}
      return VSPointerEvent()
    }
    set {_uniqueStorage()._payload = .pointerEvent(newValue)}
  }

  public var scrollEvent: VSScrollEvent {
    get {
      if case .scrollEvent(let v)? = _storage._payload {return v}
      return VSScrollEvent()
    }
    set {_uniqueStorage()._payload = .scrollEvent(newValue)}
  }

  public var keyEvent: VSKeyEvent {
    get {
      if case .keyEvent(let v)? = _storage._payload {return v}
      return VSKeyEvent()
    }
    set {_uniqueStorage()._payload = .keyEvent(newValue)}
  }

  public var inputAck: VSInputAck {
    get {
      if case .inputAck(let v)? = _storage._payload {return v}
      return VSInputAck()
    }
    set {_uniqueStorage()._payload = .inputAck(newValue)}
  }

  public var streamStats: VSStreamStats {
    get {
      if case .streamStats(let v)? = _storage._payload {return v}
      return VSStreamStats()
    }
    set {_uniqueStorage()._payload = .streamStats(newValue)}
  }

  public var transportStats: VSTransportStats {
    get {
      if case .transportStats(let v)? = _storage._payload {return v}
      return VSTransportStats()
    }
    set {_uniqueStorage()._payload = .transportStats(newValue)}
  }

  public var errorReport: VSErrorReport {
    get {
      if case .errorReport(let v)? = _storage._payload {return v}
      return VSErrorReport()
    }
    set {_uniqueStorage()._payload = .errorReport(newValue)}
  }

  public var protocolError: VSProtocolError {
    get {
      if case .protocolError(let v)? = _storage._payload {return v}
      return VSProtocolError()
    }
    set {_uniqueStorage()._payload = .protocolError(newValue)}
  }

  public var encryptedControlPacket: VSEncryptedControlPacket {
    get {
      if case .encryptedControlPacket(let v)? = _storage._payload {return v}
      return VSEncryptedControlPacket()
    }
    set {_uniqueStorage()._payload = .encryptedControlPacket(newValue)}
  }

  public var audioConfig: VSAudioConfig {
    get {
      if case .audioConfig(let v)? = _storage._payload {return v}
      return VSAudioConfig()
    }
    set {_uniqueStorage()._payload = .audioConfig(newValue)}
  }

  public var audioConfigResult: VSAudioConfigResult {
    get {
      if case .audioConfigResult(let v)? = _storage._payload {return v}
      return VSAudioConfigResult()
    }
    set {_uniqueStorage()._payload = .audioConfigResult(newValue)}
  }

  public var clipboardOffer: VSClipboardOffer {
    get {
      if case .clipboardOffer(let v)? = _storage._payload {return v}
      return VSClipboardOffer()
    }
    set {_uniqueStorage()._payload = .clipboardOffer(newValue)}
  }

  public var clipboardRequest: VSClipboardRequest {
    get {
      if case .clipboardRequest(let v)? = _storage._payload {return v}
      return VSClipboardRequest()
    }
    set {_uniqueStorage()._payload = .clipboardRequest(newValue)}
  }

  public var clipboardContent: VSClipboardContent {
    get {
      if case .clipboardContent(let v)? = _storage._payload {return v}
      return VSClipboardContent()
    }
    set {_uniqueStorage()._payload = .clipboardContent(newValue)}
  }

  public var fileOffer: VSFileOffer {
    get {
      if case .fileOffer(let v)? = _storage._payload {return v}
      return VSFileOffer()
    }
    set {_uniqueStorage()._payload = .fileOffer(newValue)}
  }

  public var fileAccept: VSFileAccept {
    get {
      if case .fileAccept(let v)? = _storage._payload {return v}
      return VSFileAccept()
    }
    set {_uniqueStorage()._payload = .fileAccept(newValue)}
  }

  public var fileTransferProgress: VSFileTransferProgress {
    get {
      if case .fileTransferProgress(let v)? = _storage._payload {return v}
      return VSFileTransferProgress()
    }
    set {_uniqueStorage()._payload = .fileTransferProgress(newValue)}
  }

  public var fileTransferCancel: VSFileTransferCancel {
    get {
      if case .fileTransferCancel(let v)? = _storage._payload {return v}
      return VSFileTransferCancel()
    }
    set {_uniqueStorage()._payload = .fileTransferCancel(newValue)}
  }

  public var fileTransferComplete: VSFileTransferComplete {
    get {
      if case .fileTransferComplete(let v)? = _storage._payload {return v}
      return VSFileTransferComplete()
    }
    set {_uniqueStorage()._payload = .fileTransferComplete(newValue)}
  }

  public var hostActionCatalog: VSHostActionCatalog {
    get {
      if case .hostActionCatalog(let v)? = _storage._payload {return v}
      return VSHostActionCatalog()
    }
    set {_uniqueStorage()._payload = .hostActionCatalog(newValue)}
  }

  public var hostActionInvoke: VSHostActionInvoke {
    get {
      if case .hostActionInvoke(let v)? = _storage._payload {return v}
      return VSHostActionInvoke()
    }
    set {_uniqueStorage()._payload = .hostActionInvoke(newValue)}
  }

  public var hostActionResult: VSHostActionResult {
    get {
      if case .hostActionResult(let v)? = _storage._payload {return v}
      return VSHostActionResult()
    }
    set {_uniqueStorage()._payload = .hostActionResult(newValue)}
  }

  public var wakeHostRequest: VSWakeHostRequest {
    get {
      if case .wakeHostRequest(let v)? = _storage._payload {return v}
      return VSWakeHostRequest()
    }
    set {_uniqueStorage()._payload = .wakeHostRequest(newValue)}
  }

  public var wakeHostResult: VSWakeHostResult {
    get {
      if case .wakeHostResult(let v)? = _storage._payload {return v}
      return VSWakeHostResult()
    }
    set {_uniqueStorage()._payload = .wakeHostResult(newValue)}
  }

  public var managedPolicyStatus: VSManagedPolicyStatus {
    get {
      if case .managedPolicyStatus(let v)? = _storage._payload {return v}
      return VSManagedPolicyStatus()
    }
    set {_uniqueStorage()._payload = .managedPolicyStatus(newValue)}
  }

  public var setVideoPreferences: VSSetVideoPreferences {
    get {
      if case .setVideoPreferences(let v)? = _storage._payload {return v}
      return VSSetVideoPreferences()
    }
    set {_uniqueStorage()._payload = .setVideoPreferences(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case clientHello(VSClientHello)
    case hostHello(VSHostHello)
    case sessionAccepted(VSSessionAccepted)
    case sessionRejected(VSSessionRejected)
    case ping(VSPing)
    case pong(VSPong)
    case resumeSessionRequest(VSResumeSessionRequest)
    case resumeSessionResult(VSResumeSessionResult)
    case disconnectNotice(VSDisconnectNotice)
    case pairingOffer(VSPairingOffer)
    case pairingRequest(VSPairingRequest)
    case pairingResult(VSPairingResult)
    case deviceRevoked(VSDeviceRevoked)
    case keyRotationRequest(VSKeyRotationRequest)
    case keyRotationResult(VSKeyRotationResult)
    case deviceRevocation(VSDeviceRevocation)
    case trafficKeyUpdate(VSTrafficKeyUpdate)
    case trafficKeyAck(VSTrafficKeyAck)
    case listDisplaysRequest(VSListDisplaysRequest)
    case listDisplaysResponse(VSListDisplaysResponse)
    case startDisplayRequest(VSStartDisplayRequest)
    case startDisplayResponse(VSStartDisplayResponse)
    case stopDisplay(VSStopDisplay)
    case displayChanged(VSDisplayChanged)
    case videoConfig(VSVideoConfig)
    case videoConfigResult(VSVideoConfigResult)
    case requestKeyframe(VSRequestKeyframe)
    case videoStreamEnded(VSVideoStreamEnded)
    case touchEvent(VSTouchEvent)
    case pointerEvent(VSPointerEvent)
    case scrollEvent(VSScrollEvent)
    case keyEvent(VSKeyEvent)
    case inputAck(VSInputAck)
    case streamStats(VSStreamStats)
    case transportStats(VSTransportStats)
    case errorReport(VSErrorReport)
    case protocolError(VSProtocolError)
    case encryptedControlPacket(VSEncryptedControlPacket)
    case audioConfig(VSAudioConfig)
    case audioConfigResult(VSAudioConfigResult)
    case clipboardOffer(VSClipboardOffer)
    case clipboardRequest(VSClipboardRequest)
    case clipboardContent(VSClipboardContent)
    case fileOffer(VSFileOffer)
    case fileAccept(VSFileAccept)
    case fileTransferProgress(VSFileTransferProgress)
    case fileTransferCancel(VSFileTransferCancel)
    case fileTransferComplete(VSFileTransferComplete)
    case hostActionCatalog(VSHostActionCatalog)
    case hostActionInvoke(VSHostActionInvoke)
    case hostActionResult(VSHostActionResult)
    case wakeHostRequest(VSWakeHostRequest)
    case wakeHostResult(VSWakeHostResult)
    case managedPolicyStatus(VSManagedPolicyStatus)
    case setVideoPreferences(VSSetVideoPreferences)

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Envelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}protocol_version\0\u{3}message_id\0\u{3}correlation_id\0\u{3}session_id\0\u{3}session_epoch\0\u{3}sent_at_monotonic_ns\0\u{4}\u{e}client_hello\0\u{3}host_hello\0\u{3}session_accepted\0\u{3}session_rejected\0\u{1}ping\0\u{1}pong\0\u{3}resume_session_request\0\u{3}resume_session_result\0\u{3}disconnect_notice\0\u{4}\u{2}pairing_offer\0\u{3}pairing_request\0\u{3}pairing_result\0\u{3}device_revoked\0\u{3}key_rotation_request\0\u{3}key_rotation_result\0\u{3}device_revocation\0\u{3}traffic_key_update\0\u{3}traffic_key_ack\0\u{4}\u{2}list_displays_request\0\u{3}list_displays_response\0\u{3}start_display_request\0\u{3}start_display_response\0\u{3}stop_display\0\u{3}display_changed\0\u{4}\u{5}video_config\0\u{3}video_config_result\0\u{3}request_keyframe\0\u{3}video_stream_ended\0\u{4}\u{7}touch_event\0\u{3}pointer_event\0\u{3}scroll_event\0\u{3}key_event\0\u{3}input_ack\0\u{4}\u{6}stream_stats\0\u{3}transport_stats\0\u{3}error_report\0\u{4}\u{8}protocol_error\0\u{4}\u{a}encrypted_control_packet\0\u{4}\u{a}audio_config\0\u{3}audio_config_result\0\u{3}clipboard_offer\0\u{3}clipboard_request\0\u{3}clipboard_content\0\u{3}file_offer\0\u{3}file_accept\0\u{3}file_transfer_progress\0\u{3}file_transfer_cancel\0\u{3}file_transfer_complete\0\u{3}host_action_catalog\0\u{3}host_action_invoke\0\u{3}host_action_result\0\u{3}wake_host_request\0\u{3}wake_host_result\0\u{3}managed_policy_status\0\u{3}set_video_preferences\0")

  fileprivate class _StorageClass {
    var _protocolVersion: UInt32 = 0
    var _messageID: UInt64 = 0
    var _correlationID: UInt64 = 0
    var _sessionID: Data = Data()
    var _sessionEpoch: UInt64 = 0
    var _sentAtMonotonicNs: UInt64 = 0
    var _payload: VSEnvelope.OneOf_Payload?

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _protocolVersion = source._protocolVersion
      _messageID = source._messageID
      _correlationID = source._correlationID
      _sessionID = source._sessionID
      _sessionEpoch = source._sessionEpoch
      _sentAtMonotonicNs = source._sentAtMonotonicNs
      _payload = source._payload
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._protocolVersion) }()
        case 2: try { try decoder.decodeSingularUInt64Field(value: &_storage._messageID) }()
        case 3: try { try decoder.decodeSingularUInt64Field(value: &_storage._correlationID) }()
        case 4: try { try decoder.decodeSingularBytesField(value: &_storage._sessionID) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._sessionEpoch) }()
        case 6: try { try decoder.decodeSingularUInt64Field(value: &_storage._sentAtMonotonicNs) }()
        case 20: try {
          var v: VSClientHello?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .clientHello(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .clientHello(v)
          }
        }()
        case 21: try {
          var v: VSHostHello?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .hostHello(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .hostHello(v)
          }
        }()
        case 22: try {
          var v: VSSessionAccepted?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .sessionAccepted(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .sessionAccepted(v)
          }
        }()
        case 23: try {
          var v: VSSessionRejected?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .sessionRejected(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .sessionRejected(v)
          }
        }()
        case 24: try {
          var v: VSPing?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .ping(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .ping(v)
          }
        }()
        case 25: try {
          var v: VSPong?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .pong(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .pong(v)
          }
        }()
        case 26: try {
          var v: VSResumeSessionRequest?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .resumeSessionRequest(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .resumeSessionRequest(v)
          }
        }()
        case 27: try {
          var v: VSResumeSessionResult?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .resumeSessionResult(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .resumeSessionResult(v)
          }
        }()
        case 28: try {
          var v: VSDisconnectNotice?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .disconnectNotice(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .disconnectNotice(v)
          }
        }()
        case 30: try {
          var v: VSPairingOffer?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .pairingOffer(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .pairingOffer(v)
          }
        }()
        case 31: try {
          var v: VSPairingRequest?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .pairingRequest(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .pairingRequest(v)
          }
        }()
        case 32: try {
          var v: VSPairingResult?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .pairingResult(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .pairingResult(v)
          }
        }()
        case 33: try {
          var v: VSDeviceRevoked?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .deviceRevoked(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .deviceRevoked(v)
          }
        }()
        case 34: try {
          var v: VSKeyRotationRequest?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .keyRotationRequest(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .keyRotationRequest(v)
          }
        }()
        case 35: try {
          var v: VSKeyRotationResult?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .keyRotationResult(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .keyRotationResult(v)
          }
        }()
        case 36: try {
          var v: VSDeviceRevocation?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .deviceRevocation(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .deviceRevocation(v)
          }
        }()
        case 37: try {
          var v: VSTrafficKeyUpdate?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .trafficKeyUpdate(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .trafficKeyUpdate(v)
          }
        }()
        case 38: try {
          var v: VSTrafficKeyAck?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .trafficKeyAck(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .trafficKeyAck(v)
          }
        }()
        case 40: try {
          var v: VSListDisplaysRequest?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .listDisplaysRequest(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .listDisplaysRequest(v)
          }
        }()
        case 41: try {
          var v: VSListDisplaysResponse?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .listDisplaysResponse(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .listDisplaysResponse(v)
          }
        }()
        case 42: try {
          var v: VSStartDisplayRequest?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .startDisplayRequest(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .startDisplayRequest(v)
          }
        }()
        case 43: try {
          var v: VSStartDisplayResponse?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .startDisplayResponse(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .startDisplayResponse(v)
          }
        }()
        case 44: try {
          var v: VSStopDisplay?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .stopDisplay(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .stopDisplay(v)
          }
        }()
        case 45: try {
          var v: VSDisplayChanged?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .displayChanged(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .displayChanged(v)
          }
        }()
        case 50: try {
          var v: VSVideoConfig?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .videoConfig(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .videoConfig(v)
          }
        }()
        case 51: try {
          var v: VSVideoConfigResult?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .videoConfigResult(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .videoConfigResult(v)
          }
        }()
        case 52: try {
          var v: VSRequestKeyframe?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .requestKeyframe(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .requestKeyframe(v)
          }
        }()
        case 53: try {
          var v: VSVideoStreamEnded?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .videoStreamEnded(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .videoStreamEnded(v)
          }
        }()
        case 60: try {
          var v: VSTouchEvent?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .touchEvent(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .touchEvent(v)
          }
        }()
        case 61: try {
          var v: VSPointerEvent?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .pointerEvent(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .pointerEvent(v)
          }
        }()
        case 62: try {
          var v: VSScrollEvent?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .scrollEvent(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .scrollEvent(v)
          }
        }()
        case 63: try {
          var v: VSKeyEvent?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .keyEvent(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .keyEvent(v)
          }
        }()
        case 64: try {
          var v: VSInputAck?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .inputAck(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .inputAck(v)
          }
        }()
        case 70: try {
          var v: VSStreamStats?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .streamStats(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .streamStats(v)
          }
        }()
        case 71: try {
          var v: VSTransportStats?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .transportStats(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .transportStats(v)
          }
        }()
        case 72: try {
          var v: VSErrorReport?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .errorReport(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .errorReport(v)
          }
        }()
        case 80: try {
          var v: VSProtocolError?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .protocolError(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .protocolError(v)
          }
        }()
        case 90: try {
          var v: VSEncryptedControlPacket?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .encryptedControlPacket(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .encryptedControlPacket(v)
          }
        }()
        case 100: try {
          var v: VSAudioConfig?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .audioConfig(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .audioConfig(v)
          }
        }()
        case 101: try {
          var v: VSAudioConfigResult?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .audioConfigResult(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .audioConfigResult(v)
          }
        }()
        case 102: try {
          var v: VSClipboardOffer?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .clipboardOffer(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .clipboardOffer(v)
          }
        }()
        case 103: try {
          var v: VSClipboardRequest?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .clipboardRequest(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .clipboardRequest(v)
          }
        }()
        case 104: try {
          var v: VSClipboardContent?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .clipboardContent(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .clipboardContent(v)
          }
        }()
        case 105: try {
          var v: VSFileOffer?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .fileOffer(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .fileOffer(v)
          }
        }()
        case 106: try {
          var v: VSFileAccept?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .fileAccept(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .fileAccept(v)
          }
        }()
        case 107: try {
          var v: VSFileTransferProgress?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .fileTransferProgress(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .fileTransferProgress(v)
          }
        }()
        case 108: try {
          var v: VSFileTransferCancel?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .fileTransferCancel(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .fileTransferCancel(v)
          }
        }()
        case 109: try {
          var v: VSFileTransferComplete?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .fileTransferComplete(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .fileTransferComplete(v)
          }
        }()
        case 110: try {
          var v: VSHostActionCatalog?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .hostActionCatalog(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .hostActionCatalog(v)
          }
        }()
        case 111: try {
          var v: VSHostActionInvoke?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .hostActionInvoke(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .hostActionInvoke(v)
          }
        }()
        case 112: try {
          var v: VSHostActionResult?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .hostActionResult(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .hostActionResult(v)
          }
        }()
        case 113: try {
          var v: VSWakeHostRequest?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .wakeHostRequest(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .wakeHostRequest(v)
          }
        }()
        case 114: try {
          var v: VSWakeHostResult?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .wakeHostResult(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .wakeHostResult(v)
          }
        }()
        case 115: try {
          var v: VSManagedPolicyStatus?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .managedPolicyStatus(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .managedPolicyStatus(v)
          }
        }()
        case 116: try {
          var v: VSSetVideoPreferences?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .setVideoPreferences(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .setVideoPreferences(v)
          }
        }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._protocolVersion != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._protocolVersion, fieldNumber: 1)
      }
      if _storage._messageID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._messageID, fieldNumber: 2)
      }
      if _storage._correlationID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._correlationID, fieldNumber: 3)
      }
      if !_storage._sessionID.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._sessionID, fieldNumber: 4)
      }
      if _storage._sessionEpoch != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._sessionEpoch, fieldNumber: 5)
      }
      if _storage._sentAtMonotonicNs != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._sentAtMonotonicNs, fieldNumber: 6)
      }
      switch _storage._payload {
      case .clientHello?: try {
        guard case .clientHello(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
      }()
      case .hostHello?: try {
        guard case .hostHello(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
      }()
      case .sessionAccepted?: try {
        guard case .sessionAccepted(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 22)
      }()
      case .sessionRejected?: try {
        guard case .sessionRejected(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 23)
      }()
      case .ping?: try {
        guard case .ping(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 24)
      }()
      case .pong?: try {
        guard case .pong(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 25)
      }()
      case .resumeSessionRequest?: try {
        guard case .resumeSessionRequest(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 26)
      }()
      case .resumeSessionResult?: try {
        guard case .resumeSessionResult(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 27)
      }()
      case .disconnectNotice?: try {
        guard case .disconnectNotice(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 28)
      }()
      case .pairingOffer?: try {
        guard case .pairingOffer(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 30)
      }()
      case .pairingRequest?: try {
        guard case .pairingRequest(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 31)
      }()
      case .pairingResult?: try {
        guard case .pairingResult(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 32)
      }()
      case .deviceRevoked?: try {
        guard case .deviceRevoked(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 33)
      }()
      case .keyRotationRequest?: try {
        guard case .keyRotationRequest(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 34)
      }()
      case .keyRotationResult?: try {
        guard case .keyRotationResult(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 35)
      }()
      case .deviceRevocation?: try {
        guard case .deviceRevocation(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 36)
      }()
      case .trafficKeyUpdate?: try {
        guard case .trafficKeyUpdate(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 37)
      }()
      case .trafficKeyAck?: try {
        guard case .trafficKeyAck(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 38)
      }()
      case .listDisplaysRequest?: try {
        guard case .listDisplaysRequest(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 40)
      }()
      case .listDisplaysResponse?: try {
        guard case .listDisplaysResponse(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 41)
      }()
      case .startDisplayRequest?: try {
        guard case .startDisplayRequest(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 42)
      }()
      case .startDisplayResponse?: try {
        guard case .startDisplayResponse(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 43)
      }()
      case .stopDisplay?: try {
        guard case .stopDisplay(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 44)
      }()
      case .displayChanged?: try {
        guard case .displayChanged(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 45)
      }()
      case .videoConfig?: try {
        guard case .videoConfig(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 50)
      }()
      case .videoConfigResult?: try {
        guard case .videoConfigResult(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 51)
      }()
      case .requestKeyframe?: try {
        guard case .requestKeyframe(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 52)
      }()
      case .videoStreamEnded?: try {
        guard case .videoStreamEnded(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 53)
      }()
      case .touchEvent?: try {
        guard case .touchEvent(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 60)
      }()
      case .pointerEvent?: try {
        guard case .pointerEvent(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 61)
      }()
      case .scrollEvent?: try {
        guard case .scrollEvent(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 62)
      }()
      case .keyEvent?: try {
        guard case .keyEvent(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 63)
      }()
      case .inputAck?: try {
        guard case .inputAck(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 64)
      }()
      case .streamStats?: try {
        guard case .streamStats(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 70)
      }()
      case .transportStats?: try {
        guard case .transportStats(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 71)
      }()
      case .errorReport?: try {
        guard case .errorReport(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 72)
      }()
      case .protocolError?: try {
        guard case .protocolError(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 80)
      }()
      case .encryptedControlPacket?: try {
        guard case .encryptedControlPacket(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 90)
      }()
      case .audioConfig?: try {
        guard case .audioConfig(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
      }()
      case .audioConfigResult?: try {
        guard case .audioConfigResult(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 101)
      }()
      case .clipboardOffer?: try {
        guard case .clipboardOffer(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 102)
      }()
      case .clipboardRequest?: try {
        guard case .clipboardRequest(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 103)
      }()
      case .clipboardContent?: try {
        guard case .clipboardContent(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 104)
      }()
      case .fileOffer?: try {
        guard case .fileOffer(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 105)
      }()
      case .fileAccept?: try {
        guard case .fileAccept(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 106)
      }()
      case .fileTransferProgress?: try {
        guard case .fileTransferProgress(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 107)
      }()
      case .fileTransferCancel?: try {
        guard case .fileTransferCancel(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 108)
      }()
      case .fileTransferComplete?: try {
        guard case .fileTransferComplete(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 109)
      }()
      case .hostActionCatalog?: try {
        guard case .hostActionCatalog(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 110)
      }()
      case .hostActionInvoke?: try {
        guard case .hostActionInvoke(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 111)
      }()
      case .hostActionResult?: try {
        guard case .hostActionResult(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 112)
      }()
      case .wakeHostRequest?: try {
        guard case .wakeHostRequest(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 113)
      }()
      case .wakeHostResult?: try {
        guard case .wakeHostResult(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 114)
      }()
      case .managedPolicyStatus?: try {
        guard case .managedPolicyStatus(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 115)
      }()
      case .setVideoPreferences?: try {
        guard case .setVideoPreferences(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 116)
      }()
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSEnvelope, rhs: VSEnvelope) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._protocolVersion != rhs_storage._protocolVersion {return false}
        if _storage._messageID != rhs_storage._messageID {return false}
        if _storage._correlationID != rhs_storage._correlationID {return false}
        if _storage._sessionID != rhs_storage._sessionID {return false}
        if _storage._sessionEpoch != rhs_storage._sessionEpoch {return false}
        if _storage._sentAtMonotonicNs != rhs_storage._sentAtMonotonicNs {return false}
        if _storage._payload != rhs_storage._payload {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
