// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/input.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum VSInputPhase: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case began // = 1
  case changed // = 2
  case ended // = 3
  case cancelled // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .began
    case 2: self = .changed
    case 3: self = .ended
    case 4: self = .cancelled
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .began: return 1
    case .changed: return 2
    case .ended: return 3
    case .cancelled: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSInputPhase] = [
    .unspecified,
    .began,
    .changed,
    .ended,
    .cancelled,
  ]

}

public enum VSStylusToolKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case pen // = 1
  case eraser // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .pen
    case 2: self = .eraser
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .pen: return 1
    case .eraser: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSStylusToolKind] = [
    .unspecified,
    .pen,
    .eraser,
  ]

}

public enum VSStylusContactState: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case contact // = 1
  case proximity // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .contact
    case 2: self = .proximity
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .contact: return 1
    case .proximity: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSStylusContactState] = [
    .unspecified,
    .contact,
    .proximity,
  ]

}

public struct VSNormalizedPoint: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var x: Double = 0

  public var y: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSTouchEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var pointerID: UInt32 = 0

  public var phase: VSInputPhase = .unspecified

  public var position: VSNormalizedPoint {
    get {return _position ?? VSNormalizedPoint()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {return self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  public var pressure: Double = 0

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _position: VSNormalizedPoint? = nil
  fileprivate var _target: VSInputTarget? = nil
}

/// Stylus pressure and tilt components must be finite. Pressure is normalized to
/// [0, 1]. Each tilt component is in [-90, 90] degrees, and the two-dimensional
/// tilt vector must satisfy hypot(tilt_x_degrees, tilt_y_degrees) <= 90 degrees.
/// Phase must be BEGAN, CHANGED, ENDED, or CANCELLED. Position coordinates must
/// be finite and normalized to [0, 1]. Extended fields require both peers to
/// negotiate CAPABILITY_STYLUS and CAPABILITY_STYLUS_EXTENDED. Without the
/// extended capability, fields 9-11 must be omitted and decode as a contacting
/// pen with no buttons, preserving the original StylusEvent behavior.
public struct VSStylusEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var pointerID: UInt32 = 0

  public var phase: VSInputPhase = .unspecified

  public var position: VSNormalizedPoint {
    get {return _position ?? VSNormalizedPoint()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {return self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  /// Normalized force. The value must be finite and in [0, 1] for BEGAN or
  /// CHANGED; it must be 0.0 for ENDED or CANCELLED.
  public var pressure: Double = 0

  /// Screen-right component of the stylus shaft's deviation from the screen
  /// normal, in degrees. The value must be finite and in [-90, 90].
  public var tiltXDegrees: Double = 0

  /// Screen-down component of the stylus shaft's deviation from the screen
  /// normal, in degrees. The value must be finite and in [-90, 90].
  public var tiltYDegrees: Double = 0

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  /// PEN or ERASER. Extended-capability senders must set this field and must not
  /// send UNSPECIFIED or an unknown enum value. Absence means PEN for backward
  /// compatibility with legacy StylusEvent messages.
  public var toolKind: VSStylusToolKind {
    get {return _toolKind ?? .unspecified}
    set {_toolKind = newValue}
  }
  /// Returns true if `toolKind` has been explicitly set.
  public var hasToolKind: Bool {return self._toolKind != nil}
  /// Clears the value of `toolKind`. Subsequent reads from it will return its default value.
  public mutating func clearToolKind() {self._toolKind = nil}

  /// Bit 0 is the primary barrel button and bit 1 is the secondary barrel
  /// button. All other bits are reserved and must be zero.
  public var buttonMask: UInt32 = 0

  /// CONTACT or PROXIMITY. Extended-capability senders must set this field and
  /// must not send UNSPECIFIED or an unknown enum value. Absence means CONTACT
  /// for backward compatibility. PROXIMITY samples must have pressure 0.0;
  /// their phase describes hover enter/change/exit.
  public var contactState: VSStylusContactState {
    get {return _contactState ?? .unspecified}
    set {_contactState = newValue}
  }
  /// Returns true if `contactState` has been explicitly set.
  public var hasContactState: Bool {return self._contactState != nil}
  /// Clears the value of `contactState`. Subsequent reads from it will return its default value.
  public mutating func clearContactState() {self._contactState = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _position: VSNormalizedPoint? = nil
  fileprivate var _target: VSInputTarget? = nil
  fileprivate var _toolKind: VSStylusToolKind? = nil
  fileprivate var _contactState: VSStylusContactState? = nil
}

public struct VSPointerEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var phase: VSInputPhase = .unspecified

  public var position: VSNormalizedPoint {
    get {return _position ?? VSNormalizedPoint()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {return self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  public var buttonMask: UInt32 = 0

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _position: VSNormalizedPoint? = nil
  fileprivate var _target: VSInputTarget? = nil
}

public struct VSScrollEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var deltaX: Double = 0

  public var deltaY: Double = 0

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _target: VSInputTarget? = nil
}

public struct VSKeyEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var usbHidUsage: UInt32 = 0

  public var pressed: Bool = false

  /// When CAPABILITY_USB_HID_MODIFIER_BYTE is negotiated, this is the standard
  /// USB HID modifier byte: bit 0 Left Control, bit 1 Left Shift, bit 2 Left
  /// Alt/Option, bit 3 Left GUI/Command, bit 4 Right Control, bit 5 Right Shift,
  /// bit 6 Right Alt/Option, and bit 7 Right GUI/Command. Without that
  /// capability, the legacy Protocol v1 layout remains bit 0 Shift, bit 1
  /// Control, bit 2 Alt/Option, and bit 3 GUI/Command; bits 4-7 are undefined
  /// and must be zero. Bits 8-31 are reserved and must be zero in either layout.
  public var modifierMask: UInt32 = 0

  public var text: String = String()

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _target: VSInputTarget? = nil
}

public struct VSInputAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var accepted: Bool = false

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSInputPhase: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INPUT_PHASE_UNSPECIFIED\0\u{1}INPUT_PHASE_BEGAN\0\u{1}INPUT_PHASE_CHANGED\0\u{1}INPUT_PHASE_ENDED\0\u{1}INPUT_PHASE_CANCELLED\0")
}

extension VSStylusToolKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STYLUS_TOOL_KIND_UNSPECIFIED\0\u{1}STYLUS_TOOL_KIND_PEN\0\u{1}STYLUS_TOOL_KIND_ERASER\0")
}

extension VSStylusContactState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STYLUS_CONTACT_STATE_UNSPECIFIED\0\u{1}STYLUS_CONTACT_STATE_CONTACT\0\u{1}STYLUS_CONTACT_STATE_PROXIMITY\0")
}

extension VSNormalizedPoint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NormalizedPoint"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.y) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.y, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSNormalizedPoint, rhs: VSNormalizedPoint) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSTouchEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TouchEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{3}pointer_id\0\u{1}phase\0\u{1}position\0\u{1}pressure\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.pointerID) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.phase) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.pressure) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.pointerID != 0 {
      try visitor.visitSingularUInt32Field(value: self.pointerID, fieldNumber: 2)
    }
    if self.phase != .unspecified {
      try visitor.visitSingularEnumField(value: self.phase, fieldNumber: 3)
    }
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if self.pressure.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.pressure, fieldNumber: 5)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSTouchEvent, rhs: VSTouchEvent) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.pointerID != rhs.pointerID {return false}
    if lhs.phase != rhs.phase {return false}
    if lhs._position != rhs._position {return false}
    if lhs.pressure != rhs.pressure {return false}
    if lhs._target != rhs._target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSStylusEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StylusEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{3}pointer_id\0\u{1}phase\0\u{1}position\0\u{1}pressure\0\u{3}tilt_x_degrees\0\u{3}tilt_y_degrees\0\u{1}target\0\u{3}tool_kind\0\u{3}button_mask\0\u{3}contact_state\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.pointerID) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.phase) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.pressure) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.tiltXDegrees) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.tiltYDegrees) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self._toolKind) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.buttonMask) }()
      case 11: try { try decoder.decodeSingularEnumField(value: &self._contactState) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.pointerID != 0 {
      try visitor.visitSingularUInt32Field(value: self.pointerID, fieldNumber: 2)
    }
    if self.phase != .unspecified {
      try visitor.visitSingularEnumField(value: self.phase, fieldNumber: 3)
    }
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if self.pressure.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.pressure, fieldNumber: 5)
    }
    if self.tiltXDegrees.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.tiltXDegrees, fieldNumber: 6)
    }
    if self.tiltYDegrees.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.tiltYDegrees, fieldNumber: 7)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._toolKind {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 9)
    } }()
    if self.buttonMask != 0 {
      try visitor.visitSingularUInt32Field(value: self.buttonMask, fieldNumber: 10)
    }
    try { if let v = self._contactState {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSStylusEvent, rhs: VSStylusEvent) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.pointerID != rhs.pointerID {return false}
    if lhs.phase != rhs.phase {return false}
    if lhs._position != rhs._position {return false}
    if lhs.pressure != rhs.pressure {return false}
    if lhs.tiltXDegrees != rhs.tiltXDegrees {return false}
    if lhs.tiltYDegrees != rhs.tiltYDegrees {return false}
    if lhs._target != rhs._target {return false}
    if lhs._toolKind != rhs._toolKind {return false}
    if lhs.buttonMask != rhs.buttonMask {return false}
    if lhs._contactState != rhs._contactState {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSPointerEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PointerEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{1}phase\0\u{1}position\0\u{3}button_mask\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.phase) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.buttonMask) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.phase != .unspecified {
      try visitor.visitSingularEnumField(value: self.phase, fieldNumber: 2)
    }
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.buttonMask != 0 {
      try visitor.visitSingularUInt32Field(value: self.buttonMask, fieldNumber: 4)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSPointerEvent, rhs: VSPointerEvent) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.phase != rhs.phase {return false}
    if lhs._position != rhs._position {return false}
    if lhs.buttonMask != rhs.buttonMask {return false}
    if lhs._target != rhs._target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSScrollEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScrollEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{3}delta_x\0\u{3}delta_y\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.deltaX) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.deltaY) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.deltaX.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.deltaX, fieldNumber: 2)
    }
    if self.deltaY.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.deltaY, fieldNumber: 3)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSScrollEvent, rhs: VSScrollEvent) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.deltaX != rhs.deltaX {return false}
    if lhs.deltaY != rhs.deltaY {return false}
    if lhs._target != rhs._target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSKeyEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{3}usb_hid_usage\0\u{1}pressed\0\u{3}modifier_mask\0\u{1}text\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.usbHidUsage) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.pressed) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.modifierMask) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.usbHidUsage != 0 {
      try visitor.visitSingularUInt32Field(value: self.usbHidUsage, fieldNumber: 2)
    }
    if self.pressed != false {
      try visitor.visitSingularBoolField(value: self.pressed, fieldNumber: 3)
    }
    if self.modifierMask != 0 {
      try visitor.visitSingularUInt32Field(value: self.modifierMask, fieldNumber: 4)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 5)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSKeyEvent, rhs: VSKeyEvent) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.usbHidUsage != rhs.usbHidUsage {return false}
    if lhs.pressed != rhs.pressed {return false}
    if lhs.modifierMask != rhs.modifierMask {return false}
    if lhs.text != rhs.text {return false}
    if lhs._target != rhs._target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSInputAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputAck"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{1}accepted\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 2)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSInputAck, rhs: VSInputAck) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
