// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/input.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum VSInputPhase: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case began // = 1
  case changed // = 2
  case ended // = 3
  case cancelled // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .began
    case 2: self = .changed
    case 3: self = .ended
    case 4: self = .cancelled
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .began: return 1
    case .changed: return 2
    case .ended: return 3
    case .cancelled: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSInputPhase] = [
    .unspecified,
    .began,
    .changed,
    .ended,
    .cancelled,
  ]

}

public struct VSNormalizedPoint: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var x: Double = 0

  public var y: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSTouchEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var pointerID: UInt32 = 0

  public var phase: VSInputPhase = .unspecified

  public var position: VSNormalizedPoint {
    get {return _position ?? VSNormalizedPoint()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {return self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  public var pressure: Double = 0

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _position: VSNormalizedPoint? = nil
  fileprivate var _target: VSInputTarget? = nil
}

public struct VSPointerEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var phase: VSInputPhase = .unspecified

  public var position: VSNormalizedPoint {
    get {return _position ?? VSNormalizedPoint()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {return self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  public var buttonMask: UInt32 = 0

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _position: VSNormalizedPoint? = nil
  fileprivate var _target: VSInputTarget? = nil
}

public struct VSScrollEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var deltaX: Double = 0

  public var deltaY: Double = 0

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _target: VSInputTarget? = nil
}

public struct VSKeyEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var usbHidUsage: UInt32 = 0

  public var pressed: Bool = false

  public var modifierMask: UInt32 = 0

  public var text: String = String()

  public var target: VSInputTarget {
    get {return _target ?? VSInputTarget()}
    set {_target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {return self._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {self._target = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _target: VSInputTarget? = nil
}

public struct VSInputAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inputID: UInt64 = 0

  public var accepted: Bool = false

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSInputPhase: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INPUT_PHASE_UNSPECIFIED\0\u{1}INPUT_PHASE_BEGAN\0\u{1}INPUT_PHASE_CHANGED\0\u{1}INPUT_PHASE_ENDED\0\u{1}INPUT_PHASE_CANCELLED\0")
}

extension VSNormalizedPoint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NormalizedPoint"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.y) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.y, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSNormalizedPoint, rhs: VSNormalizedPoint) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSTouchEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TouchEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{3}pointer_id\0\u{1}phase\0\u{1}position\0\u{1}pressure\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.pointerID) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.phase) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.pressure) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.pointerID != 0 {
      try visitor.visitSingularUInt32Field(value: self.pointerID, fieldNumber: 2)
    }
    if self.phase != .unspecified {
      try visitor.visitSingularEnumField(value: self.phase, fieldNumber: 3)
    }
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if self.pressure.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.pressure, fieldNumber: 5)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSTouchEvent, rhs: VSTouchEvent) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.pointerID != rhs.pointerID {return false}
    if lhs.phase != rhs.phase {return false}
    if lhs._position != rhs._position {return false}
    if lhs.pressure != rhs.pressure {return false}
    if lhs._target != rhs._target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSPointerEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PointerEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{1}phase\0\u{1}position\0\u{3}button_mask\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.phase) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.buttonMask) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.phase != .unspecified {
      try visitor.visitSingularEnumField(value: self.phase, fieldNumber: 2)
    }
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.buttonMask != 0 {
      try visitor.visitSingularUInt32Field(value: self.buttonMask, fieldNumber: 4)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSPointerEvent, rhs: VSPointerEvent) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.phase != rhs.phase {return false}
    if lhs._position != rhs._position {return false}
    if lhs.buttonMask != rhs.buttonMask {return false}
    if lhs._target != rhs._target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSScrollEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScrollEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{3}delta_x\0\u{3}delta_y\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.deltaX) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.deltaY) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.deltaX.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.deltaX, fieldNumber: 2)
    }
    if self.deltaY.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.deltaY, fieldNumber: 3)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSScrollEvent, rhs: VSScrollEvent) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.deltaX != rhs.deltaX {return false}
    if lhs.deltaY != rhs.deltaY {return false}
    if lhs._target != rhs._target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSKeyEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{3}usb_hid_usage\0\u{1}pressed\0\u{3}modifier_mask\0\u{1}text\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.usbHidUsage) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.pressed) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.modifierMask) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.usbHidUsage != 0 {
      try visitor.visitSingularUInt32Field(value: self.usbHidUsage, fieldNumber: 2)
    }
    if self.pressed != false {
      try visitor.visitSingularBoolField(value: self.pressed, fieldNumber: 3)
    }
    if self.modifierMask != 0 {
      try visitor.visitSingularUInt32Field(value: self.modifierMask, fieldNumber: 4)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 5)
    }
    try { if let v = self._target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSKeyEvent, rhs: VSKeyEvent) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.usbHidUsage != rhs.usbHidUsage {return false}
    if lhs.pressed != rhs.pressed {return false}
    if lhs.modifierMask != rhs.modifierMask {return false}
    if lhs.text != rhs.text {return false}
    if lhs._target != rhs._target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSInputAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputAck"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_id\0\u{1}accepted\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.inputID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.inputID != 0 {
      try visitor.visitSingularUInt64Field(value: self.inputID, fieldNumber: 1)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 2)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSInputAck, rhs: VSInputAck) -> Bool {
    if lhs.inputID != rhs.inputID {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
