// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/security.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum VSSignatureAlgorithm: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case ecdsaP256Sha256 // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .ecdsaP256Sha256
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .ecdsaP256Sha256: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSSignatureAlgorithm] = [
    .unspecified,
    .ecdsaP256Sha256,
  ]

}

public enum VSKeyAgreementAlgorithm: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case ecdhP256 // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .ecdhP256
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .ecdhP256: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSKeyAgreementAlgorithm] = [
    .unspecified,
    .ecdhP256,
  ]

}

public enum VSAeadAlgorithm: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case aes256Gcm // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .aes256Gcm
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .aes256Gcm: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSAeadAlgorithm] = [
    .unspecified,
    .aes256Gcm,
  ]

}

public enum VSSecureChannel: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case control // = 1
  case media // = 2
  case audio // = 3
  case bulk // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .control
    case 2: self = .media
    case 3: self = .audio
    case 4: self = .bulk
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .control: return 1
    case .media: return 2
    case .audio: return 3
    case .bulk: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSSecureChannel] = [
    .unspecified,
    .control,
    .media,
    .audio,
    .bulk,
  ]

}

public enum VSSenderRole: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case host // = 1
  case device // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .host
    case 2: self = .device
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .host: return 1
    case .device: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSSenderRole] = [
    .unspecified,
    .host,
    .device,
  ]

}

public struct VSDeviceIdentity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: String = String()

  public var keyID: String = String()

  public var keyEpoch: UInt64 = 0

  public var signatureAlgorithm: VSSignatureAlgorithm = .unspecified

  public var signingPublicKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSPairingProof: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var challenge: Data = Data()

  public var ephemeralPublicKey: Data = Data()

  public var signature: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSKeyRotationRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var currentIdentity: VSDeviceIdentity {
    get {return _currentIdentity ?? VSDeviceIdentity()}
    set {_currentIdentity = newValue}
  }
  /// Returns true if `currentIdentity` has been explicitly set.
  public var hasCurrentIdentity: Bool {return self._currentIdentity != nil}
  /// Clears the value of `currentIdentity`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentIdentity() {self._currentIdentity = nil}

  public var nextIdentity: VSDeviceIdentity {
    get {return _nextIdentity ?? VSDeviceIdentity()}
    set {_nextIdentity = newValue}
  }
  /// Returns true if `nextIdentity` has been explicitly set.
  public var hasNextIdentity: Bool {return self._nextIdentity != nil}
  /// Clears the value of `nextIdentity`. Subsequent reads from it will return its default value.
  public mutating func clearNextIdentity() {self._nextIdentity = nil}

  public var rotationNonce: Data = Data()

  public var notBeforeUnixSeconds: UInt64 = 0

  public var currentKeySignature: Data = Data()

  public var nextKeySignature: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _currentIdentity: VSDeviceIdentity? = nil
  fileprivate var _nextIdentity: VSDeviceIdentity? = nil
}

public struct VSKeyRotationResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accepted: Bool = false

  public var deviceID: String = String()

  public var activeKeyID: String = String()

  public var activeKeyEpoch: UInt64 = 0

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// TrafficKeyUpdate is sent inside an authenticated EncryptedControlPacket.
/// Receivers derive the next directional control/media keys, acknowledge, then
/// retire the prior epoch after their bounded reordering grace window.
public struct VSTrafficKeyUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var currentKeyID: String = String()

  public var currentKeyEpoch: UInt64 = 0

  public var nextKeyEpoch: UInt64 = 0

  public var updateNonce: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSTrafficKeyAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var activeKeyID: String = String()

  public var activeKeyEpoch: UInt64 = 0

  public var accepted: Bool = false

  public var rejectionReason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSDeviceRevocation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: String = String()

  public var keyID: String = String()

  public var revocationSequence: UInt64 = 0

  public var revokedAtUnixSeconds: UInt64 = 0

  public var revocationNonce: Data = Data()

  public var reasonCode: String = String()

  public var authority: VSDeviceIdentity {
    get {return _authority ?? VSDeviceIdentity()}
    set {_authority = newValue}
  }
  /// Returns true if `authority` has been explicitly set.
  public var hasAuthority: Bool {return self._authority != nil}
  /// Clears the value of `authority`. Subsequent reads from it will return its default value.
  public mutating func clearAuthority() {self._authority = nil}

  public var authoritySignature: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _authority: VSDeviceIdentity? = nil
}

public struct VSSecurePacketHeader: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var protocolVersion: UInt32 = 0

  public var sessionID: Data = Data()

  public var sessionEpoch: UInt64 = 0

  public var keyID: String = String()

  public var keyEpoch: UInt64 = 0

  public var channel: VSSecureChannel = .unspecified

  public var sequence: UInt64 = 0

  public var aeadAlgorithm: VSAeadAlgorithm = .unspecified

  public var nonce: Data = Data()

  public var senderRole: VSSenderRole = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSEncryptedControlPacket: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var header: VSSecurePacketHeader {
    get {return _header ?? VSSecurePacketHeader()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {self._header = nil}

  public var ciphertext: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _header: VSSecurePacketHeader? = nil
}

/// EncryptedMediaPacket remains on the independent, unordered media channel.
/// The ciphertext contains MediaPacketHeader followed by the encoded payload so
/// a relay cannot inspect frame metadata or screen content.
public struct VSEncryptedMediaPacket: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var header: VSSecurePacketHeader {
    get {return _header ?? VSSecurePacketHeader()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  public var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  public mutating func clearHeader() {self._header = nil}

  public var ciphertext: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _header: VSSecurePacketHeader? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSSignatureAlgorithm: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SIGNATURE_ALGORITHM_UNSPECIFIED\0\u{1}SIGNATURE_ALGORITHM_ECDSA_P256_SHA256\0")
}

extension VSKeyAgreementAlgorithm: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0KEY_AGREEMENT_ALGORITHM_UNSPECIFIED\0\u{1}KEY_AGREEMENT_ALGORITHM_ECDH_P256\0")
}

extension VSAeadAlgorithm: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AEAD_ALGORITHM_UNSPECIFIED\0\u{1}AEAD_ALGORITHM_AES_256_GCM\0")
}

extension VSSecureChannel: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SECURE_CHANNEL_UNSPECIFIED\0\u{1}SECURE_CHANNEL_CONTROL\0\u{1}SECURE_CHANNEL_MEDIA\0\u{1}SECURE_CHANNEL_AUDIO\0\u{1}SECURE_CHANNEL_BULK\0")
}

extension VSSenderRole: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SENDER_ROLE_UNSPECIFIED\0\u{1}SENDER_ROLE_HOST\0\u{1}SENDER_ROLE_DEVICE\0")
}

extension VSDeviceIdentity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceIdentity"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{3}key_id\0\u{3}key_epoch\0\u{3}signature_algorithm\0\u{3}signing_public_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.keyID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.keyEpoch) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.signatureAlgorithm) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.signingPublicKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 1)
    }
    if !self.keyID.isEmpty {
      try visitor.visitSingularStringField(value: self.keyID, fieldNumber: 2)
    }
    if self.keyEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.keyEpoch, fieldNumber: 3)
    }
    if self.signatureAlgorithm != .unspecified {
      try visitor.visitSingularEnumField(value: self.signatureAlgorithm, fieldNumber: 4)
    }
    if !self.signingPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.signingPublicKey, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSDeviceIdentity, rhs: VSDeviceIdentity) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.keyEpoch != rhs.keyEpoch {return false}
    if lhs.signatureAlgorithm != rhs.signatureAlgorithm {return false}
    if lhs.signingPublicKey != rhs.signingPublicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSPairingProof: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairingProof"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}challenge\0\u{3}ephemeral_public_key\0\u{1}signature\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.challenge) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.ephemeralPublicKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.challenge.isEmpty {
      try visitor.visitSingularBytesField(value: self.challenge, fieldNumber: 1)
    }
    if !self.ephemeralPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.ephemeralPublicKey, fieldNumber: 2)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSPairingProof, rhs: VSPairingProof) -> Bool {
    if lhs.challenge != rhs.challenge {return false}
    if lhs.ephemeralPublicKey != rhs.ephemeralPublicKey {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSKeyRotationRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyRotationRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}current_identity\0\u{3}next_identity\0\u{3}rotation_nonce\0\u{3}not_before_unix_seconds\0\u{3}current_key_signature\0\u{3}next_key_signature\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._currentIdentity) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._nextIdentity) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.rotationNonce) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.notBeforeUnixSeconds) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.currentKeySignature) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.nextKeySignature) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._currentIdentity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._nextIdentity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.rotationNonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.rotationNonce, fieldNumber: 3)
    }
    if self.notBeforeUnixSeconds != 0 {
      try visitor.visitSingularUInt64Field(value: self.notBeforeUnixSeconds, fieldNumber: 4)
    }
    if !self.currentKeySignature.isEmpty {
      try visitor.visitSingularBytesField(value: self.currentKeySignature, fieldNumber: 5)
    }
    if !self.nextKeySignature.isEmpty {
      try visitor.visitSingularBytesField(value: self.nextKeySignature, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSKeyRotationRequest, rhs: VSKeyRotationRequest) -> Bool {
    if lhs._currentIdentity != rhs._currentIdentity {return false}
    if lhs._nextIdentity != rhs._nextIdentity {return false}
    if lhs.rotationNonce != rhs.rotationNonce {return false}
    if lhs.notBeforeUnixSeconds != rhs.notBeforeUnixSeconds {return false}
    if lhs.currentKeySignature != rhs.currentKeySignature {return false}
    if lhs.nextKeySignature != rhs.nextKeySignature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSKeyRotationResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyRotationResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}accepted\0\u{3}device_id\0\u{3}active_key_id\0\u{3}active_key_epoch\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.activeKeyID) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.activeKeyEpoch) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 2)
    }
    if !self.activeKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.activeKeyID, fieldNumber: 3)
    }
    if self.activeKeyEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.activeKeyEpoch, fieldNumber: 4)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSKeyRotationResult, rhs: VSKeyRotationResult) -> Bool {
    if lhs.accepted != rhs.accepted {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.activeKeyID != rhs.activeKeyID {return false}
    if lhs.activeKeyEpoch != rhs.activeKeyEpoch {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSTrafficKeyUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TrafficKeyUpdate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}current_key_id\0\u{3}current_key_epoch\0\u{3}next_key_epoch\0\u{3}update_nonce\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.currentKeyID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.currentKeyEpoch) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.nextKeyEpoch) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.updateNonce) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.currentKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.currentKeyID, fieldNumber: 1)
    }
    if self.currentKeyEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.currentKeyEpoch, fieldNumber: 2)
    }
    if self.nextKeyEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.nextKeyEpoch, fieldNumber: 3)
    }
    if !self.updateNonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.updateNonce, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSTrafficKeyUpdate, rhs: VSTrafficKeyUpdate) -> Bool {
    if lhs.currentKeyID != rhs.currentKeyID {return false}
    if lhs.currentKeyEpoch != rhs.currentKeyEpoch {return false}
    if lhs.nextKeyEpoch != rhs.nextKeyEpoch {return false}
    if lhs.updateNonce != rhs.updateNonce {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSTrafficKeyAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TrafficKeyAck"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}active_key_id\0\u{3}active_key_epoch\0\u{1}accepted\0\u{3}rejection_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.activeKeyID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.activeKeyEpoch) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.activeKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.activeKeyID, fieldNumber: 1)
    }
    if self.activeKeyEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.activeKeyEpoch, fieldNumber: 2)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 3)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSTrafficKeyAck, rhs: VSTrafficKeyAck) -> Bool {
    if lhs.activeKeyID != rhs.activeKeyID {return false}
    if lhs.activeKeyEpoch != rhs.activeKeyEpoch {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSDeviceRevocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceRevocation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_id\0\u{3}key_id\0\u{3}revocation_sequence\0\u{3}revoked_at_unix_seconds\0\u{3}revocation_nonce\0\u{3}reason_code\0\u{1}authority\0\u{3}authority_signature\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.keyID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.revocationSequence) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.revokedAtUnixSeconds) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.revocationNonce) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._authority) }()
      case 8: try { try decoder.decodeSingularBytesField(value: &self.authoritySignature) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 1)
    }
    if !self.keyID.isEmpty {
      try visitor.visitSingularStringField(value: self.keyID, fieldNumber: 2)
    }
    if self.revocationSequence != 0 {
      try visitor.visitSingularUInt64Field(value: self.revocationSequence, fieldNumber: 3)
    }
    if self.revokedAtUnixSeconds != 0 {
      try visitor.visitSingularUInt64Field(value: self.revokedAtUnixSeconds, fieldNumber: 4)
    }
    if !self.revocationNonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.revocationNonce, fieldNumber: 5)
    }
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 6)
    }
    try { if let v = self._authority {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    if !self.authoritySignature.isEmpty {
      try visitor.visitSingularBytesField(value: self.authoritySignature, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSDeviceRevocation, rhs: VSDeviceRevocation) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.revocationSequence != rhs.revocationSequence {return false}
    if lhs.revokedAtUnixSeconds != rhs.revokedAtUnixSeconds {return false}
    if lhs.revocationNonce != rhs.revocationNonce {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs._authority != rhs._authority {return false}
    if lhs.authoritySignature != rhs.authoritySignature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSSecurePacketHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SecurePacketHeader"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}protocol_version\0\u{3}session_id\0\u{3}session_epoch\0\u{3}key_id\0\u{3}key_epoch\0\u{1}channel\0\u{1}sequence\0\u{3}aead_algorithm\0\u{1}nonce\0\u{3}sender_role\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.protocolVersion) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.sessionID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.sessionEpoch) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.keyID) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.keyEpoch) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.channel) }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self.sequence) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self.aeadAlgorithm) }()
      case 9: try { try decoder.decodeSingularBytesField(value: &self.nonce) }()
      case 10: try { try decoder.decodeSingularEnumField(value: &self.senderRole) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.protocolVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.protocolVersion, fieldNumber: 1)
    }
    if !self.sessionID.isEmpty {
      try visitor.visitSingularBytesField(value: self.sessionID, fieldNumber: 2)
    }
    if self.sessionEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionEpoch, fieldNumber: 3)
    }
    if !self.keyID.isEmpty {
      try visitor.visitSingularStringField(value: self.keyID, fieldNumber: 4)
    }
    if self.keyEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.keyEpoch, fieldNumber: 5)
    }
    if self.channel != .unspecified {
      try visitor.visitSingularEnumField(value: self.channel, fieldNumber: 6)
    }
    if self.sequence != 0 {
      try visitor.visitSingularUInt64Field(value: self.sequence, fieldNumber: 7)
    }
    if self.aeadAlgorithm != .unspecified {
      try visitor.visitSingularEnumField(value: self.aeadAlgorithm, fieldNumber: 8)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.nonce, fieldNumber: 9)
    }
    if self.senderRole != .unspecified {
      try visitor.visitSingularEnumField(value: self.senderRole, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSSecurePacketHeader, rhs: VSSecurePacketHeader) -> Bool {
    if lhs.protocolVersion != rhs.protocolVersion {return false}
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.sessionEpoch != rhs.sessionEpoch {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.keyEpoch != rhs.keyEpoch {return false}
    if lhs.channel != rhs.channel {return false}
    if lhs.sequence != rhs.sequence {return false}
    if lhs.aeadAlgorithm != rhs.aeadAlgorithm {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.senderRole != rhs.senderRole {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSEncryptedControlPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EncryptedControlPacket"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{1}ciphertext\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._header) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.ciphertext) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._header {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.ciphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.ciphertext, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSEncryptedControlPacket, rhs: VSEncryptedControlPacket) -> Bool {
    if lhs._header != rhs._header {return false}
    if lhs.ciphertext != rhs.ciphertext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSEncryptedMediaPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EncryptedMediaPacket"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}header\0\u{1}ciphertext\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._header) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.ciphertext) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._header {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.ciphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.ciphertext, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSEncryptedMediaPacket, rhs: VSEncryptedMediaPacket) -> Bool {
    if lhs._header != rhs._header {return false}
    if lhs.ciphertext != rhs.ciphertext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
