// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/telemetry.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct VSStreamStats: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt64 = 0

  public var capturedFps: Double = 0

  public var encodedFps: Double = 0

  public var renderedFps: Double = 0

  public var droppedBeforeEncode: UInt64 = 0

  public var droppedBeforeSend: UInt64 = 0

  public var mediaQueueDepth: UInt32 = 0

  public var encodeTimeP95Ms: Double = 0

  public var decodeTimeP95Ms: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSTransportStats: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var bytesSent: UInt64 = 0

  public var bytesReceived: UInt64 = 0

  public var roundTripTimeMs: Double = 0

  public var reconnectCount: UInt64 = 0

  public var lastReconnectTimeMs: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSErrorReport: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var code: String = String()

  public var component: String = String()

  public var message: String = String()

  public var retryable: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSStreamStats: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamStats"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}captured_fps\0\u{3}encoded_fps\0\u{3}rendered_fps\0\u{3}dropped_before_encode\0\u{3}dropped_before_send\0\u{3}media_queue_depth\0\u{3}encode_time_p95_ms\0\u{3}decode_time_p95_ms\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.capturedFps) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.encodedFps) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.renderedFps) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.droppedBeforeEncode) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.droppedBeforeSend) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.mediaQueueDepth) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self.encodeTimeP95Ms) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self.decodeTimeP95Ms) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 1)
    }
    if self.capturedFps.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.capturedFps, fieldNumber: 2)
    }
    if self.encodedFps.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.encodedFps, fieldNumber: 3)
    }
    if self.renderedFps.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.renderedFps, fieldNumber: 4)
    }
    if self.droppedBeforeEncode != 0 {
      try visitor.visitSingularUInt64Field(value: self.droppedBeforeEncode, fieldNumber: 5)
    }
    if self.droppedBeforeSend != 0 {
      try visitor.visitSingularUInt64Field(value: self.droppedBeforeSend, fieldNumber: 6)
    }
    if self.mediaQueueDepth != 0 {
      try visitor.visitSingularUInt32Field(value: self.mediaQueueDepth, fieldNumber: 7)
    }
    if self.encodeTimeP95Ms.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.encodeTimeP95Ms, fieldNumber: 8)
    }
    if self.decodeTimeP95Ms.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.decodeTimeP95Ms, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSStreamStats, rhs: VSStreamStats) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.capturedFps != rhs.capturedFps {return false}
    if lhs.encodedFps != rhs.encodedFps {return false}
    if lhs.renderedFps != rhs.renderedFps {return false}
    if lhs.droppedBeforeEncode != rhs.droppedBeforeEncode {return false}
    if lhs.droppedBeforeSend != rhs.droppedBeforeSend {return false}
    if lhs.mediaQueueDepth != rhs.mediaQueueDepth {return false}
    if lhs.encodeTimeP95Ms != rhs.encodeTimeP95Ms {return false}
    if lhs.decodeTimeP95Ms != rhs.decodeTimeP95Ms {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSTransportStats: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TransportStats"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}bytes_sent\0\u{3}bytes_received\0\u{3}round_trip_time_ms\0\u{3}reconnect_count\0\u{3}last_reconnect_time_ms\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.bytesSent) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.bytesReceived) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.roundTripTimeMs) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.reconnectCount) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.lastReconnectTimeMs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.bytesSent != 0 {
      try visitor.visitSingularUInt64Field(value: self.bytesSent, fieldNumber: 1)
    }
    if self.bytesReceived != 0 {
      try visitor.visitSingularUInt64Field(value: self.bytesReceived, fieldNumber: 2)
    }
    if self.roundTripTimeMs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.roundTripTimeMs, fieldNumber: 3)
    }
    if self.reconnectCount != 0 {
      try visitor.visitSingularUInt64Field(value: self.reconnectCount, fieldNumber: 4)
    }
    if self.lastReconnectTimeMs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.lastReconnectTimeMs, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSTransportStats, rhs: VSTransportStats) -> Bool {
    if lhs.bytesSent != rhs.bytesSent {return false}
    if lhs.bytesReceived != rhs.bytesReceived {return false}
    if lhs.roundTripTimeMs != rhs.roundTripTimeMs {return false}
    if lhs.reconnectCount != rhs.reconnectCount {return false}
    if lhs.lastReconnectTimeMs != rhs.lastReconnectTimeMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSErrorReport: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ErrorReport"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}component\0\u{1}message\0\u{1}retryable\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.component) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.retryable) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    if !self.component.isEmpty {
      try visitor.visitSingularStringField(value: self.component, fieldNumber: 2)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 3)
    }
    if self.retryable != false {
      try visitor.visitSingularBoolField(value: self.retryable, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSErrorReport, rhs: VSErrorReport) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.component != rhs.component {return false}
    if lhs.message != rhs.message {return false}
    if lhs.retryable != rhs.retryable {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
