// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vibescreen/protocol/v1/video.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Coarse client-selectable quality intent. The host maps a preset to its
/// internal encoder quality when the client does not request an explicit
/// bitrate, so clients can express intent without knowing host encoder units.
public enum VSVideoQualityPreset: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case smooth // = 1
  case balanced // = 2
  case sharp // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .smooth
    case 2: self = .balanced
    case 3: self = .sharp
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .smooth: return 1
    case .balanced: return 2
    case .sharp: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VSVideoQualityPreset] = [
    .unspecified,
    .smooth,
    .balanced,
    .sharp,
  ]

}

public struct VSVideoConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var configEpoch: UInt64 = 0

  public var codec: VSCodec = .unspecified

  public var encodedSize: VSDimensions {
    get {return _encodedSize ?? VSDimensions()}
    set {_encodedSize = newValue}
  }
  /// Returns true if `encodedSize` has been explicitly set.
  public var hasEncodedSize: Bool {return self._encodedSize != nil}
  /// Clears the value of `encodedSize`. Subsequent reads from it will return its default value.
  public mutating func clearEncodedSize() {self._encodedSize = nil}

  public var framesPerSecond: UInt32 = 0

  public var bitrateKbps: UInt32 = 0

  public var streamID: UInt64 = 0

  public var colorDescription: VSColorDescription {
    get {return _colorDescription ?? VSColorDescription()}
    set {_colorDescription = newValue}
  }
  /// Returns true if `colorDescription` has been explicitly set.
  public var hasColorDescription: Bool {return self._colorDescription != nil}
  /// Clears the value of `colorDescription`. Subsequent reads from it will return its default value.
  public mutating func clearColorDescription() {self._colorDescription = nil}

  public var rotationDegrees: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _encodedSize: VSDimensions? = nil
  fileprivate var _colorDescription: VSColorDescription? = nil
}

public struct VSVideoConfigResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var configEpoch: UInt64 = 0

  public var accepted: Bool = false

  public var rejectionReason: String = String()

  public var streamID: UInt64 = 0

  public var selectedColorDescription: VSColorDescription {
    get {return _selectedColorDescription ?? VSColorDescription()}
    set {_selectedColorDescription = newValue}
  }
  /// Returns true if `selectedColorDescription` has been explicitly set.
  public var hasSelectedColorDescription: Bool {return self._selectedColorDescription != nil}
  /// Clears the value of `selectedColorDescription`. Subsequent reads from it will return its default value.
  public mutating func clearSelectedColorDescription() {self._selectedColorDescription = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _selectedColorDescription: VSColorDescription? = nil
}

/// Client-driven video tuning request sent to the host on the active session.
/// Every field is optional so a client can adjust one dimension at a time; an
/// unset field leaves the corresponding host setting unchanged. The host
/// clamps values to the negotiated capabilities and its supported range, then
/// re-advertises the applied VideoConfig with a bumped config_epoch. Requires
/// the CAPABILITY_CLIENT_VIDEO_CONTROL capability to be negotiated.
public struct VSSetVideoPreferences: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Requested encoder bitrate in kbps. 0 leaves the current bitrate unchanged.
  public var bitrateKbps: UInt32 = 0

  /// Requested capture/encode frame rate. 0 leaves the current rate unchanged.
  public var framesPerSecond: UInt32 = 0

  /// Coarse quality intent applied when no explicit bitrate is requested.
  public var qualityPreset: VSVideoQualityPreset = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSRequestKeyframe: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt64 = 0

  public var reasonCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSVideoStreamEnded: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt64 = 0

  public var reasonCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VSMediaPacketHeader: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt64 = 0

  public var sessionEpoch: UInt64 = 0

  public var configEpoch: UInt64 = 0

  public var frameID: UInt64 = 0

  public var fragmentIndex: UInt32 = 0

  public var fragmentCount: UInt32 = 0

  public var captureTimestampNs: UInt64 = 0

  public var keyframe: Bool = false

  public var codec: VSCodec = .unspecified

  public var payloadLength: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vibescreen.protocol.v1"

extension VSVideoQualityPreset: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0VIDEO_QUALITY_PRESET_UNSPECIFIED\0\u{1}VIDEO_QUALITY_PRESET_SMOOTH\0\u{1}VIDEO_QUALITY_PRESET_BALANCED\0\u{1}VIDEO_QUALITY_PRESET_SHARP\0")
}

extension VSVideoConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}config_epoch\0\u{1}codec\0\u{3}encoded_size\0\u{3}frames_per_second\0\u{3}bitrate_kbps\0\u{3}stream_id\0\u{3}color_description\0\u{3}rotation_degrees\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.configEpoch) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.codec) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._encodedSize) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.framesPerSecond) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.bitrateKbps) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._colorDescription) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.rotationDegrees) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.configEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.configEpoch, fieldNumber: 1)
    }
    if self.codec != .unspecified {
      try visitor.visitSingularEnumField(value: self.codec, fieldNumber: 2)
    }
    try { if let v = self._encodedSize {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.framesPerSecond != 0 {
      try visitor.visitSingularUInt32Field(value: self.framesPerSecond, fieldNumber: 4)
    }
    if self.bitrateKbps != 0 {
      try visitor.visitSingularUInt32Field(value: self.bitrateKbps, fieldNumber: 5)
    }
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 6)
    }
    try { if let v = self._colorDescription {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    if self.rotationDegrees != 0 {
      try visitor.visitSingularUInt32Field(value: self.rotationDegrees, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSVideoConfig, rhs: VSVideoConfig) -> Bool {
    if lhs.configEpoch != rhs.configEpoch {return false}
    if lhs.codec != rhs.codec {return false}
    if lhs._encodedSize != rhs._encodedSize {return false}
    if lhs.framesPerSecond != rhs.framesPerSecond {return false}
    if lhs.bitrateKbps != rhs.bitrateKbps {return false}
    if lhs.streamID != rhs.streamID {return false}
    if lhs._colorDescription != rhs._colorDescription {return false}
    if lhs.rotationDegrees != rhs.rotationDegrees {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSVideoConfigResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoConfigResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}config_epoch\0\u{1}accepted\0\u{3}rejection_reason\0\u{3}stream_id\0\u{3}selected_color_description\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.configEpoch) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rejectionReason) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._selectedColorDescription) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.configEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.configEpoch, fieldNumber: 1)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 2)
    }
    if !self.rejectionReason.isEmpty {
      try visitor.visitSingularStringField(value: self.rejectionReason, fieldNumber: 3)
    }
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 4)
    }
    try { if let v = self._selectedColorDescription {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSVideoConfigResult, rhs: VSVideoConfigResult) -> Bool {
    if lhs.configEpoch != rhs.configEpoch {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.rejectionReason != rhs.rejectionReason {return false}
    if lhs.streamID != rhs.streamID {return false}
    if lhs._selectedColorDescription != rhs._selectedColorDescription {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSSetVideoPreferences: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetVideoPreferences"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}bitrate_kbps\0\u{3}frames_per_second\0\u{3}quality_preset\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.bitrateKbps) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.framesPerSecond) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.qualityPreset) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.bitrateKbps != 0 {
      try visitor.visitSingularUInt32Field(value: self.bitrateKbps, fieldNumber: 1)
    }
    if self.framesPerSecond != 0 {
      try visitor.visitSingularUInt32Field(value: self.framesPerSecond, fieldNumber: 2)
    }
    if self.qualityPreset != .unspecified {
      try visitor.visitSingularEnumField(value: self.qualityPreset, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSSetVideoPreferences, rhs: VSSetVideoPreferences) -> Bool {
    if lhs.bitrateKbps != rhs.bitrateKbps {return false}
    if lhs.framesPerSecond != rhs.framesPerSecond {return false}
    if lhs.qualityPreset != rhs.qualityPreset {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSRequestKeyframe: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestKeyframe"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}reason_code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 1)
    }
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSRequestKeyframe, rhs: VSRequestKeyframe) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSVideoStreamEnded: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoStreamEnded"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}reason_code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reasonCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 1)
    }
    if !self.reasonCode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonCode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSVideoStreamEnded, rhs: VSVideoStreamEnded) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VSMediaPacketHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MediaPacketHeader"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}session_epoch\0\u{3}config_epoch\0\u{3}frame_id\0\u{3}fragment_index\0\u{3}fragment_count\0\u{3}capture_timestamp_ns\0\u{1}keyframe\0\u{1}codec\0\u{3}payload_length\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.sessionEpoch) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.configEpoch) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.frameID) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.fragmentIndex) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.fragmentCount) }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self.captureTimestampNs) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.keyframe) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self.codec) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.payloadLength) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt64Field(value: self.streamID, fieldNumber: 1)
    }
    if self.sessionEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionEpoch, fieldNumber: 2)
    }
    if self.configEpoch != 0 {
      try visitor.visitSingularUInt64Field(value: self.configEpoch, fieldNumber: 3)
    }
    if self.frameID != 0 {
      try visitor.visitSingularUInt64Field(value: self.frameID, fieldNumber: 4)
    }
    if self.fragmentIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.fragmentIndex, fieldNumber: 5)
    }
    if self.fragmentCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.fragmentCount, fieldNumber: 6)
    }
    if self.captureTimestampNs != 0 {
      try visitor.visitSingularUInt64Field(value: self.captureTimestampNs, fieldNumber: 7)
    }
    if self.keyframe != false {
      try visitor.visitSingularBoolField(value: self.keyframe, fieldNumber: 8)
    }
    if self.codec != .unspecified {
      try visitor.visitSingularEnumField(value: self.codec, fieldNumber: 9)
    }
    if self.payloadLength != 0 {
      try visitor.visitSingularUInt32Field(value: self.payloadLength, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSMediaPacketHeader, rhs: VSMediaPacketHeader) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.sessionEpoch != rhs.sessionEpoch {return false}
    if lhs.configEpoch != rhs.configEpoch {return false}
    if lhs.frameID != rhs.frameID {return false}
    if lhs.fragmentIndex != rhs.fragmentIndex {return false}
    if lhs.fragmentCount != rhs.fragmentCount {return false}
    if lhs.captureTimestampNs != rhs.captureTimestampNs {return false}
    if lhs.keyframe != rhs.keyframe {return false}
    if lhs.codec != rhs.codec {return false}
    if lhs.payloadLength != rhs.payloadLength {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
